// ═══════════════════════════════════════════════════════════
// BIVOUAC PYRÉNÉES & PAYS BASQUE — Shared Data (v2 — édition complète)
// ═══════════════════════════════════════════════════════════
// 25 circuits bivouac · 16 randos journée
// Niveaux : facile · modere · difficile · expert
// Zones : paysbasque · pyrenees · ariege · orientales
// ═══════════════════════════════════════════════════════════

const CIRCUITS = [

  // ──────────────────────────────────────────────────────────
  // ★ FACILE — DÉBUTANTS
  // ──────────────────────────────────────────────────────────

  {
    id: 1, slug: "lacs-ayous",
    emoji: "🏔️", title: "Tour des Lacs d'Ayous",
    region: "Vallée d'Ossau (64)", zone: "pyrenees",
    level: "facile", levelLabel: "Facile+", levelColor: "#52b788",
    jours: 2, kmJour: 10, totalKm: 20, denivelé: 1100,
    saison: "Juin – octobre",
    img: "https://images.unsplash.com/photo-1609766857823-56b5f81a7d67?w=1200&q=85",
    imgThumb: "https://images.unsplash.com/photo-1609766857823-56b5f81a7d67?w=600&q=75",
    depart: "Parking lac de Bious-Artigues — Gabas (64440)",
    acces: "Depuis Pau : 1h15 · Depuis Bayonne : 1h45",
    sommet: "Col d'Ayous (2 185 m)",
    balisage: "GR 10 rouge/blanc — balisage irréprochable",
    eau: "Nombreuses sources et lacs — eau potable après filtration",
    ravito: "Aucun en chemin · Village de Laruns (25 km)",
    carte: "IGN Top 25 · 1547 OT",
    description: "Le lac d'Ayous est l'un des joyaux des Pyrénées béarnaises. Face au Pic du Midi d'Ossau qui se reflète dans ses eaux émeraude, ce circuit en boucle facile offre un bivouac d'exception pour une première nuit en altitude. Le coucher de soleil sur le Midi d'Ossau depuis la rive du lac Bersau est une expérience rare.",
    etapes: [
      { jour: "J1", troncon: "Bious-Artigues → Lac d'Ayous → Col d'Ayous → Lac Bersau", km: "10 km", deni: "+1 100/−300 m", bivouac: "Rive du lac Bersau (2 083 m) — plat, abrité, vue sur le Midi d'Ossau" },
      { jour: "J2", troncon: "Lac Bersau → Lac Roumassot → Lac de Casterau → Bious-Artigues", km: "10 km", deni: "+100/−900 m", bivouac: "Retour au point de départ" },
    ],
    tips: [
      "Le lac d'Ayous offre l'un des plus beaux couchers de soleil des Pyrénées, face au Pic du Midi d'Ossau.",
      "Le J2 est en descente : parfait quand on est un peu fatigués le deuxième jour !",
      "Balisage GR 10 irréprochable — impossible de se perdre, même sans GPS.",
      "Zone fréquentée : rassurante pour un premier bivouac.",
    ],
    links: [
      { icon: "⛺", label: "Refuge d'Ayous", url: "https://www.refuge-ayous.com", note: "Plan B si mauvais temps" },
      { icon: "🗺️", label: "Wikiloc – Lacs d'Ayous", url: "https://fr.wikiloc.com/itineraires-randonnee-pedestres/tour-des-lacs-d-ayous", note: "Trace GPS" },
      { icon: "📷", label: "Altituderando", url: "https://www.altituderando.com/Tour-des-lacs-d-Ayous", note: "Photos + description" },
      { icon: "🌤️", label: "Météo montagne", url: "https://meteofrance.com/meteo-montagne/pyrenees", note: "À consulter la veille" },
    ],
    highlights: ["Vue iconique sur le Midi d'Ossau", "Lacs d'altitude émeraude", "Idéal premier bivouac"],
  },

  {
    id: 2, slug: "crete-iparla",
    emoji: "🌿", title: "Crête d'Iparla – Boucle basque",
    region: "Pays Basque intérieur (64)", zone: "paysbasque",
    level: "facile", levelLabel: "Facile+", levelColor: "#52b788",
    jours: 2, kmJour: 11, totalKm: 22, denivelé: 1000,
    saison: "Avril – novembre",
    img: "https://images.unsplash.com/photo-1499856871958-5b9357976b82?w=1200&q=85",
    imgThumb: "https://images.unsplash.com/photo-1499856871958-5b9357976b82?w=600&q=75",
    depart: "Village de Bidarray (64780) — parking de l'église, gratuit",
    acces: "Depuis Bayonne : 40 min · Depuis Pau : 1h30",
    sommet: "Crête d'Iparla (1 044 m)",
    balisage: "Sentiers balisés jaune-rouge + GR 10",
    eau: "Sources rares en été — emportez 2L/pers min.",
    ravito: "Bidarray : boulangerie, épicerie, restaurants",
    carte: "IGN Top 25 · 1346 OT",
    description: "La crête d'Iparla est l'une des plus belles lignes de crête du Pays Basque. Pelouses rases, pottoks en liberté et vue à 360° sur l'Atlantique d'un côté, les Pyrénées de l'autre. Un bivouac dans les étoiles sur les hauts plateaux basques, accessible dès le premier week-end.",
    etapes: [
      { jour: "J1", troncon: "Bidarray → Montée crête d'Iparla → Sommet Artzamendi Nord", km: "11 km", deni: "+1 000/−200 m", bivouac: "Crête d'Iparla (900–1 000 m) — pelouses rases, vue 360°" },
      { jour: "J2", troncon: "Crête → Col de Harrieta → Forêt de Hayra → Bidarray", km: "11 km", deni: "+200/−1 000 m", bivouac: "Retour au point de départ" },
    ],
    tips: [
      "Pelouses basques, moutons, pottoks et vue sur l'Atlantique — ambiance totalement différente des Pyrénées.",
      "Bivouac sur les pelouses de crête : herbe rase, terrain plat naturel.",
      "Le village de Bidarray est charmant — parfait pour un dîner le soir du retour.",
      "Vent souvent fort sur les crêtes — prévoir un abri léger ou choisir un repli.",
    ],
    links: [
      { icon: "🗺️", label: "Visorando – Crête d'Iparla", url: "https://www.visorando.com/randonnee-crete-d-iparla", note: "Description + photos" },
      { icon: "📍", label: "AllTrails – Iparla Ridge", url: "https://www.alltrails.com/trail/france/pyrenees-atlantiques/iparla-ridge", note: "Carte interactive" },
      { icon: "🌤️", label: "Météo Bidarray", url: "https://meteofrance.com/previsions-meteo-france/bidarray/64780", note: "Prévisions locales" },
    ],
    highlights: ["Vue sur l'Atlantique", "Pottoks en liberté", "Village basque authentique"],
  },

  {
    id: 3, slug: "foret-iraty",
    emoji: "🌲", title: "Tour de la Forêt d'Iraty",
    region: "Pays Basque / Pyrénées (64)", zone: "paysbasque",
    level: "facile", levelLabel: "Facile", levelColor: "#52b788",
    jours: 3, kmJour: 10, totalKm: 30, denivelé: 1200,
    saison: "Mai – octobre",
    img: "https://images.unsplash.com/photo-1448375240586-882707db888b?w=1200&q=85",
    imgThumb: "https://images.unsplash.com/photo-1448375240586-882707db888b?w=600&q=75",
    depart: "Chalet Pedro, Plateau d'Iraty (64560)",
    acces: "Depuis Bayonne : 1h30 · Depuis Pau : 1h45",
    sommet: "Col Bagargui (1 327 m)",
    balisage: "GR 10 + sentiers forestiers jaune",
    eau: "Rivières et fontaines — eau très abondante",
    ravito: "Chalet Pedro (restaurant, épicerie sommaire)",
    carte: "IGN Top 25 · 1346 OT",
    description: "Iraty, c'est la plus grande hêtraie-sapinière d'Europe occidentale. Trois jours dans cette cathédrale végétale, entre forêts profondes, estives ouvertes et vestiges romains. Un bivouac hors du commun, enveloppé par les arbres — idéal pour les groupes et les familles.",
    etapes: [
      { jour: "J1", troncon: "Chalet Pedro → Forêt d'Iraty → Lac Arphia → Col Bagargui", km: "10 km", deni: "+600/−200 m", bivouac: "Bords du lac Arphia (1 265 m) — lac en forêt" },
      { jour: "J2", troncon: "Col Bagargui → Crête des Urculu → Tour d'Urculu → Estive", km: "10 km", deni: "+500/−400 m", bivouac: "Estives d'Orgambidexka (1 300 m)" },
      { jour: "J3", troncon: "Orgambidexka → Forêt de Soule → Chalet Pedro", km: "10 km", deni: "+100/−700 m", bivouac: "Retour au point de départ" },
    ],
    tips: [
      "La forêt d'Iraty est la plus grande hêtraie-sapinière d'Europe — ambiance forestière magique.",
      "La Tour d'Urculu (J2) est un ancien fortin romain — belle surprise culturelle.",
      "Accessible sans jamais dépasser 1 350 m — aucun risque lié à l'altitude.",
      "Vaches et brebis omniprésentes sur les estives — gardez vos distances.",
    ],
    links: [
      { icon: "🌲", label: "Site officiel Iraty", url: "https://www.paysbasque-foret-iraty.com", note: "Cartes + infos" },
      { icon: "🏠", label: "Chalet Pedro", url: "https://www.chaletpedro.com", note: "Plan B" },
      { icon: "📷", label: "Altituderando – Iraty", url: "https://www.altituderando.com/La-foret-d-Iraty", note: "Photos de saison" },
    ],
    highlights: ["Plus grande forêt d'Europe occidentale", "Fortin romain Urculu", "Dénivelés très doux"],
  },

  {
    id: 4, slug: "artouste-soussouéou",
    emoji: "🦅", title: "Boucle Lac d'Artouste & Soussouéou",
    region: "Vallée d'Ossau (64)", zone: "pyrenees",
    level: "modere", levelLabel: "Modéré", levelColor: "#e9c46a",
    jours: 3, kmJour: 10, totalKm: 30, denivelé: 1500,
    saison: "Juillet – septembre",
    img: "https://images.unsplash.com/photo-1506905925346-21bda4d32df4?w=1200&q=85",
    imgThumb: "https://images.unsplash.com/photo-1506905925346-21bda4d32df4?w=600&q=75",
    depart: "Fabrèges (64440) — parking téléphérique d'Artouste",
    acces: "Depuis Pau : 1h20 · Depuis Bayonne : 1h50",
    sommet: "Hourquette d'Arre (2 465 m)",
    balisage: "GR 10 + sentiers balisés Ossau",
    eau: "Nombreux lacs et ruisseaux — eau abondante",
    ravito: "Aucun en chemin (3 jours de nourriture)",
    carte: "IGN Top 25 · 1547 OT",
    description: "Montez au lac d'Artouste en petit train centenaire, puis descendez à travers des paysages de lacs sauvages et de cascades. Ce circuit combine le plus haut train touristique de France avec deux nuits de bivouac dans des paysages exceptionnels.",
    etapes: [
      { jour: "J1", troncon: "Fabrèges → Train d'Artouste → Lac d'Artouste → Lac d'Arrious", km: "10 km", deni: "+400/−200 m", bivouac: "Lac d'Arrious (2 072 m)" },
      { jour: "J2", troncon: "Lac d'Arrious → Hourquette d'Arre → Lacs de Soussouéou", km: "10 km", deni: "+600/−1 100 m", bivouac: "Bords du gave de Soussouéou (1 350 m)" },
      { jour: "J3", troncon: "Soussouéou → Sentier des cascades → Fabrèges", km: "10 km", deni: "+400/−650 m", bivouac: "Retour au point de départ" },
    ],
    tips: [
      "Le train d'Artouste est unique : le plus haut train touristique de France (1 950 m). Réservez à l'avance !",
      "Les lacs de Soussouéou sont peu fréquentés — spots de bivouac de rêve.",
      "Le retour par les cascades de Soussouéou est spectaculaire.",
    ],
    links: [
      { icon: "🚂", label: "Train d'Artouste", url: "https://www.artouste.com", note: "Réservation obligatoire" },
      { icon: "🗺️", label: "Wikiloc – Soussouéou", url: "https://fr.wikiloc.com/itineraires/lacs-de-soussoueoeu-ossau", note: "Traces GPS" },
      { icon: "📷", label: "Altituderando – Arrious", url: "https://www.altituderando.com/Lac-d-Arrious", note: "Fiche détaillée" },
    ],
    highlights: ["Train touristique à 1 950 m", "Cascades de Soussouéou", "Lacs sauvages peu fréquentés"],
  },

  {
    id: 25, slug: "boucle-sainte-engrace",
    emoji: "🌊", title: "Gorges de Kakuetta & Boucle Sainte-Engrâce",
    region: "Soule · Pays Basque (64)", zone: "paysbasque",
    level: "facile", levelLabel: "Facile", levelColor: "#52b788",
    jours: 2, kmJour: 9, totalKm: 18, denivelé: 750,
    saison: "Avril – novembre",
    img: "https://images.unsplash.com/photo-1418065460487-3e41a6c84dc5?w=1200&q=85",
    imgThumb: "https://images.unsplash.com/photo-1418065460487-3e41a6c84dc5?w=600&q=75",
    depart: "Sainte-Engrâce (64560) — parking village",
    acces: "Depuis Mauléon-Licharre : 45 min · Depuis Bayonne : 1h45",
    sommet: "Belvédère de Kanibeleta (1 200 m)",
    balisage: "Sentiers PR balisés jaune — bien indiqué",
    eau: "Gave de Sainte-Engrâce abondant — fontaines au village",
    ravito: "Sainte-Engrâce : auberge, restaurant",
    carte: "IGN Top 25 · 1346 OT",
    description: "La Soule, province oubliée du Pays Basque, recèle des trésors cachés. Les gorges de Kakuetta, classées parmi les plus belles de France, s'ouvrent à quelques pas du village de Sainte-Engrâce. Un bivouac tranquille entre canyon et prairie d'altitude.",
    etapes: [
      { jour: "J1", troncon: "Sainte-Engrâce → Gorges de Kakuetta → Plateau de Larrau", km: "9 km", deni: "+750/−100 m", bivouac: "Plateau de Larrau (1 100 m) — herbe rase, vues Pyrénées" },
      { jour: "J2", troncon: "Larrau → Belvédère de Kanibeleta → Retour Sainte-Engrâce", km: "9 km", deni: "+100/−750 m", bivouac: "Retour au point de départ" },
    ],
    tips: [
      "Les gorges de Kakuetta nécessitent de traverser deux fois le gave — portez des sandales de rivière.",
      "Bivouac sur le plateau de Larrau : terrain parfait, très peu fréquenté.",
      "La Soule est la province basque la moins touristique — authenticité garantie.",
    ],
    links: [
      { icon: "🌊", label: "Gorges de Kakuetta", url: "https://www.gorges-kakuetta.com", note: "Horaires + tarifs" },
      { icon: "🗺️", label: "Rando Pays Basque", url: "https://rando-pays-basque.info/soule/", note: "Topos locaux" },
    ],
    highlights: ["Gorges de Kakuetta (parmi les + belles de France)", "Pays basque authentique", "Idéal familles"],
  },

  {
    id: 26, slug: "boucle-ossau-gabas",
    emoji: "🦌", title: "Boucle Gabas – Lac de Fabrèges",
    region: "Vallée d'Ossau (64)", zone: "pyrenees",
    level: "facile", levelLabel: "Facile", levelColor: "#52b788",
    jours: 2, kmJour: 8, totalKm: 16, denivelé: 600,
    saison: "Mai – octobre",
    img: "https://images.unsplash.com/photo-1501854140801-50d01698950b?w=1200&q=85",
    imgThumb: "https://images.unsplash.com/photo-1501854140801-50d01698950b?w=600&q=75",
    depart: "Gabas (64440) — parking du village",
    acces: "Depuis Pau : 1h10 · Depuis Tarbes : 1h20",
    sommet: "Belvédère du lac de Fabrèges (1 247 m)",
    balisage: "Sentiers PR jaune + GR 10 court tronçon",
    eau: "Gave d'Ossau, lac de Fabrèges, sources multiples",
    ravito: "Gabas : épicerie, auberge",
    carte: "IGN Top 25 · 1547 OT",
    description: "Un premier bivouac extrêmement accessible dans la vallée d'Ossau. Le lac de Fabrèges, retenue artificielle entourée de montagnes, offre un cadre serein. Parfait pour les familles avec enfants dès 8 ans ou pour tester son équipement avant un circuit plus engagé.",
    etapes: [
      { jour: "J1", troncon: "Gabas → Sentier des isards → Belvédère lac de Fabrèges", km: "8 km", deni: "+600/−0 m", bivouac: "Prairie au-dessus du lac (1 250 m) — terrain facile" },
      { jour: "J2", troncon: "Lac de Fabrèges → Col de Bious → Retour Gabas", km: "8 km", deni: "+100/−600 m", bivouac: "Retour au point de départ" },
    ],
    tips: [
      "Circuit parfait pour tester son équipement de bivouac pour la première fois.",
      "Les isards sont souvent visibles au crépuscule sur les versants rocheux.",
      "Gabas propose une épicerie — rechargez-y en eau et ravitaillement.",
    ],
    links: [
      { icon: "🌿", label: "Vallée d'Ossau Tourisme", url: "https://www.ossau-pyrenees.com/randonnees", note: "Topos officiels" },
      { icon: "📷", label: "Altituderando – Ossau", url: "https://www.altituderando.com/Vallee-d-Ossau", note: "Fiches + photos" },
    ],
    highlights: ["Idéal premier bivouac / familles", "Isards souvent visibles", "Très accessible"],
  },

  // ──────────────────────────────────────────────────────────
  // ★ MODÉRÉ — RANDONNEURS RÉGULIERS
  // ──────────────────────────────────────────────────────────

  {
    id: 5, slug: "pays-basque-interieur",
    emoji: "🌿", title: "Tour du Pays Basque intérieur",
    region: "Pays Basque · France", zone: "paysbasque",
    level: "modere", levelLabel: "Modéré", levelColor: "#e9c46a",
    jours: 3, kmJour: 18, totalKm: 55, denivelé: 2400,
    saison: "Mai – octobre",
    img: "https://images.unsplash.com/photo-1469474968028-56623f02e42e?w=1200&q=85",
    imgThumb: "https://images.unsplash.com/photo-1469474968028-56623f02e42e?w=600&q=75",
    depart: "Saint-Jean-Pied-de-Port (64220) — parking porte Saint-Jacques",
    acces: "Depuis Bayonne : 55 min · Depuis Pau : 1h20",
    sommet: "Sommet d'Occabé (1 456 m)",
    balisage: "GR 10 + sentiers locaux jaune",
    eau: "Sources en altitude, villages de Banca et Aldudes",
    ravito: "Villages traversés : Banca, Aldudes",
    carte: "IGN Top 25 · 1346 OT",
    description: "Au départ de Saint-Jean-Pied-de-Port, porte des pèlerins de Compostelle, ce tour traverse le cœur du Pays Basque intérieur. Crêtes, estives, villages typiques et panoramas sur l'Atlantique composent un itinéraire à la fois physique et culturel.",
    etapes: [
      { jour: "J1", troncon: "Saint-Jean-Pied-de-Port → Col d'Ursuia → Crête d'Iparla", km: "18 km", deni: "+1 050/−250 m", bivouac: "Crête d'Iparla (1 044 m)" },
      { jour: "J2", troncon: "Crête d'Iparla → Forêt d'Hayra → Sommet d'Occabé", km: "20 km", deni: "+950/−700 m", bivouac: "Plateau sous Occabé (1 350 m)" },
      { jour: "J3", troncon: "Occabé → Col de Burdincurutcheta → Saint-Jean-Pied-de-Port", km: "17 km", deni: "+400/−1 450 m", bivouac: "Retour au point de départ" },
    ],
    tips: [
      "Remplissez vos gourdes au départ : les sources sont parfois taries en été.",
      "La crête d'Iparla est exposée au vent — prévoyez un abri léger.",
      "Ce circuit peut se raccourcir en 2 jours pour les plus rapides.",
    ],
    links: [
      { icon: "🗺️", label: "IGNrando", url: "https://ignrando.fr/fr/communautes-et-parcours/detail-un-parcours?id=53791", note: "Trace GPS officielle" },
      { icon: "📷", label: "Visorando", url: "https://www.visorando.com/randonnee-tour-du-pays-basque/", note: "Description + photos" },
      { icon: "🌤️", label: "Météo Pyrénées", url: "https://meteofrance.com/meteo-montagne/pyrenees", note: "Prévisions" },
    ],
    highlights: ["Départ depuis Saint-Jean-Pied-de-Port", "Villages basques authentiques", "Crêtes et estives"],
  },

  {
    id: 7, slug: "lacs-ossau",
    emoji: "🦅", title: "Tour des Lacs d'Ossau",
    region: "Vallée d'Ossau · Béarn (64)", zone: "pyrenees",
    level: "modere", levelLabel: "Modéré", levelColor: "#e9c46a",
    jours: 3, kmJour: 17, totalKm: 52, denivelé: 3100,
    saison: "Juin – octobre",
    img: "https://images.unsplash.com/photo-1501854140801-50d01698950b?w=1200&q=85",
    imgThumb: "https://images.unsplash.com/photo-1501854140801-50d01698950b?w=600&q=75",
    depart: "Gabas (64440) — parking lac de Bious-Artigues",
    acces: "Depuis Pau : 1h15 · Depuis Bayonne : 1h45",
    sommet: "Col de Peyreget (2 208 m)",
    balisage: "GR 10 + sentiers balisés Ossau",
    eau: "Lacs de Bious, d'Anglas, de Peyreget",
    ravito: "Cabane de Peyreget (non gardée)",
    carte: "IGN Top 25 · 1547 OT",
    description: "Un enchaînement de lacs d'altitude comme nulle part ailleurs dans les Pyrénées. Chaque soir, le bivouac se fait au bord d'un lac différent, sous le regard permanent du Pic du Midi d'Ossau — le « Jean-Pierre » des locaux.",
    etapes: [
      { jour: "J1", troncon: "Bious-Artigues → Lacs d'Ayous → Col d'Ayous", km: "17 km", deni: "+1 150/−350 m", bivouac: "Lac d'Ayous (2 185 m)" },
      { jour: "J2", troncon: "Col d'Ayous → Lac de Bersau → Lac d'Anglas → Col d'Anglas", km: "19 km", deni: "+1 100/−950 m", bivouac: "Lac d'Anglas (2 065 m)" },
      { jour: "J3", troncon: "Col d'Anglas → Lac de Peyreget → Col de Peyreget → Bious-Artigues", km: "16 km", deni: "+850/−1 750 m", bivouac: "Retour au point de départ" },
    ],
    tips: [
      "Évitez ce circuit par temps d'orage : les crêtes sont très exposées à la foudre.",
      "Les isards et vautours fauves sont fréquents — emportez des jumelles.",
      "Nuit différente à chaque étape : 3 lacs, 3 atmosphères.",
    ],
    links: [
      { icon: "⛺", label: "Refuge d'Ayous", url: "https://www.refuge-ayous.com", note: "Gardé, dortoirs" },
      { icon: "🗺️", label: "Wikiloc – Ossau", url: "https://fr.wikiloc.com/itineraires-randonnee-pedestres/tour-des-lacs-ossau", note: "GPS track" },
      { icon: "🌿", label: "Vallée d'Ossau Tourisme", url: "https://www.ossau-pyrenees.com/randonnees", note: "Infos locales" },
    ],
    highlights: ["3 lacs en 3 nuits", "Isards et vautours fauves", "Pic du Midi d'Ossau omniprésent"],
  },

  {
    id: 27, slug: "tour-pays-toy",
    emoji: "🌋", title: "Tour du Pays Toy – Gavarnie",
    region: "Hautes-Pyrénées (65)", zone: "pyrenees",
    level: "modere", levelLabel: "Modéré", levelColor: "#e9c46a",
    jours: 3, kmJour: 14, totalKm: 42, denivelé: 2800,
    saison: "Juin – septembre",
    img: "https://images.unsplash.com/photo-1464822759023-fed622ff2c3b?w=1200&q=85",
    imgThumb: "https://images.unsplash.com/photo-1464822759023-fed622ff2c3b?w=600&q=75",
    depart: "Gavarnie (65120) — parking village",
    acces: "Depuis Tarbes : 1h30 · Depuis Pau : 1h45",
    sommet: "Col de la Bernatoire (2 060 m)",
    balisage: "GR 10 + sentiers locaux — bien balisé",
    eau: "Sources nombreuses, gave de Gavarnie",
    ravito: "Gavarnie : commerces et restaurants",
    carte: "IGN Top 25 · 1748 OT",
    description: "Gavarnie et son cirque classé UNESCO fascinent depuis le XIXe siècle. Ce tour du Pays Toy vous emmène hors des sentiers battus : crêtes peu fréquentées, plateaux en fleurs et vues plongeantes sur le cirque de Gavarnie depuis ses rebords. La grande cascade de 423 m vous accompagne deux soirs.",
    etapes: [
      { jour: "J1", troncon: "Gavarnie → Cirque de Gavarnie → Col de la Bernatoire → Plateau", km: "14 km", deni: "+1 100/−200 m", bivouac: "Plateau de la Bernatoire (2 000 m) — vue cirque" },
      { jour: "J2", troncon: "Plateau → Hourquette d'Alans → Estaubé → Héas", km: "14 km", deni: "+950/−1 050 m", bivouac: "Vallée d'Estaubé (1 500 m) — rivière" },
      { jour: "J3", troncon: "Héas → Col de Mesdames → Retour Gavarnie", km: "14 km", deni: "+750/−1 550 m", bivouac: "Retour au point de départ" },
    ],
    tips: [
      "Gavarnie est très fréquenté — partez tôt le matin pour profiter du cirque sans la foule.",
      "La vallée d'Estaubé (J2) est encore confidentielle malgré sa beauté exceptionnelle.",
      "La grande cascade de Gavarnie (423 m) est visible depuis le plateau de la Bernatoire.",
    ],
    links: [
      { icon: "🏞️", label: "Parc National Pyrénées", url: "https://www.pyrenees-parcnational.fr", note: "Réglementation bivouac" },
      { icon: "🗺️", label: "Altituderando – Gavarnie", url: "https://www.altituderando.com/Cirque-de-Gavarnie", note: "Photos + fiches" },
      { icon: "📷", label: "Wikiloc – Gavarnie", url: "https://fr.wikiloc.com/itineraires/gavarnie-65", note: "Traces GPS" },
    ],
    highlights: ["Cirque de Gavarnie UNESCO", "Grande cascade (423 m)", "Vallée d'Estaubé confidentielle"],
  },

  {
    id: 28, slug: "tour-neouveille",
    emoji: "💎", title: "Tour du Néouvielle",
    region: "Hautes-Pyrénées (65)", zone: "pyrenees",
    level: "modere", levelLabel: "Modéré+", levelColor: "#e9c46a",
    jours: 4, kmJour: 13, totalKm: 52, denivelé: 3200,
    saison: "Juillet – septembre",
    img: "https://images.unsplash.com/photo-1506905925346-21bda4d32df4?w=1200&q=85",
    imgThumb: "https://images.unsplash.com/photo-1506905925346-21bda4d32df4?w=600&q=75",
    depart: "Lac d'Orédon (65170) — parking, accès D929 depuis Aragnouet",
    acces: "Depuis Tarbes : 1h45 · Depuis Pau : 2h",
    sommet: "Soum de Maucapéra (2 826 m)",
    balisage: "Sentiers balisés RNR + GR 10 · Parfois cairns",
    eau: "Dizaines de lacs — eau abondante",
    ravito: "Aucun en chemin · Aragnouet pour les provisions",
    carte: "IGN Top 25 · 1748 OT",
    description: "La Réserve Naturelle du Néouvielle, c'est plus de 70 lacs dans un massif granitique solitaire. Quatre jours immergé dans ce labyrinthe aquatique où l'on ne croise presque personne après le premier lac. L'un des circuits les plus spectaculaires des Pyrénées sans dépasser 3 000 m.",
    etapes: [
      { jour: "J1", troncon: "Lac d'Orédon → Lac de Cap-de-Long → Lac d'Aubert", km: "12 km", deni: "+900/−300 m", bivouac: "Lac d'Aubert (2 350 m)" },
      { jour: "J2", troncon: "Lac d'Aubert → Soum de Maucapéra → Lac de la Glère", km: "13 km", deni: "+950/−850 m", bivouac: "Lac de la Glère (2 350 m)" },
      { jour: "J3", troncon: "Lac de la Glère → Cols du massif → Lacs de Barroude", km: "14 km", deni: "+800/−750 m", bivouac: "Barroude (2 370 m)" },
      { jour: "J4", troncon: "Barroude → Lac d'Orédon par versant est", km: "13 km", deni: "+550/−1 350 m", bivouac: "Retour au point de départ" },
    ],
    tips: [
      "La Réserve du Néouvielle est protégée — respectez strictement les zones de bivouac autorisées.",
      "Accès routier à l'Orédon restreint en juillet-août : navette depuis Aragnouet recommandée.",
      "Portez des guêtres : beaucoup de passages humides entre les lacs.",
    ],
    links: [
      { icon: "🌿", label: "Réserve Néouvielle", url: "https://www.reserves-naturelles.org/neouvielle", note: "Réglementation + faune" },
      { icon: "🗺️", label: "Altituderando – Néouvielle", url: "https://www.altituderando.com/Neouveille", note: "Fiches + photos" },
      { icon: "📍", label: "AllTrails – Néouvielle", url: "https://www.alltrails.com/fr/randonnee/france/hautes-pyrenees/neouvielle", note: "Avis + traces" },
    ],
    highlights: ["70+ lacs dans la réserve", "Sauvagerie totale", "Pas de 3 000 m requis"],
  },

  {
    id: 29, slug: "chemin-saint-jacques-soule",
    emoji: "🏡", title: "Boucle Soule – Chemin de Compostelle",
    region: "Soule · Basse-Navarre (64)", zone: "paysbasque",
    level: "modere", levelLabel: "Modéré", levelColor: "#e9c46a",
    jours: 3, kmJour: 16, totalKm: 48, denivelé: 2000,
    saison: "Avril – octobre",
    img: "https://images.unsplash.com/photo-1469474968028-56623f02e42e?w=1200&q=85",
    imgThumb: "https://images.unsplash.com/photo-1469474968028-56623f02e42e?w=600&q=75",
    depart: "Mauléon-Licharre (64130) — parking centre-ville",
    acces: "Depuis Bayonne : 1h · Depuis Pau : 1h",
    sommet: "Col d'Ahüsquy (1 101 m)",
    balisage: "GR 65 Compostelle + sentiers Soule jaune",
    eau: "Villages nombreux, rivières de Soule",
    ravito: "Villages : Tardets, Musculdy, Gotein",
    carte: "IGN Top 25 · 1345 OT",
    description: "La Soule est la province basque la moins connue — et la plus attachante. Ce tour emprunte des tronçons du chemin de Compostelle, traverse des villages de stèles discoïdales et dort dans des prairies où seuls les cloches des brebis troublent le silence. Culture basque à l'état pur.",
    etapes: [
      { jour: "J1", troncon: "Mauléon → Col de Burdincurutcheta → Tardets", km: "16 km", deni: "+750/−600 m", bivouac: "Prairie au-dessus de Tardets (600 m)" },
      { jour: "J2", troncon: "Tardets → Col d'Ahüsquy → Forêt de Mendi", km: "17 km", deni: "+850/−750 m", bivouac: "Forêt de Mendi (900 m) — sous les hêtres" },
      { jour: "J3", troncon: "Mendi → Musculdy → Gotein → Mauléon", km: "15 km", deni: "+400/−900 m", bivouac: "Retour au point de départ" },
    ],
    tips: [
      "Les stèles discoïdales basques (xillarri) jalonnent les cimetières traversés — patrimoine unique.",
      "Le fromage de brebis de Soule (Ossau-Iraty) est disponible dans les fermes traversées.",
      "Ce circuit est idéal au printemps quand les hêtraies bourgeonnent.",
    ],
    links: [
      { icon: "🗺️", label: "Rando Pays Basque Soule", url: "https://rando-pays-basque.info/soule/", note: "Topos locaux" },
      { icon: "📷", label: "Tourisme Soule", url: "https://www.tourisme-soule.com/randonnees.php", note: "Infos pratiques" },
    ],
    highlights: ["Province basque authentique", "Fromages de brebis AOP", "Stèles discoïdales basques"],
  },

  {
    id: 30, slug: "haute-ariege-beille",
    emoji: "🐺", title: "Plateau de Beille & Haute Ariège",
    region: "Ariège (09)", zone: "ariege",
    level: "modere", levelLabel: "Modéré", levelColor: "#e9c46a",
    jours: 3, kmJour: 15, totalKm: 45, denivelé: 2600,
    saison: "Juin – septembre",
    img: "https://images.unsplash.com/photo-1519681393784-d120267933ba?w=1200&q=85",
    imgThumb: "https://images.unsplash.com/photo-1519681393784-d120267933ba?w=600&q=75",
    depart: "Les Cabannes (09310) — parking gare",
    acces: "Depuis Foix : 35 min · Depuis Toulouse : 1h30",
    sommet: "Pic de Rulhe (2 783 m)",
    balisage: "GR 10 + sentiers locaux balisés",
    eau: "Nombreux ruisseaux et sources",
    ravito: "Les Cabannes, Auzat",
    carte: "IGN Top 25 · 2148 OT",
    description: "L'Ariège, pays des cathares et des loups revenus. Le plateau de Beille ouvre sur un monde pastoral suspendu entre forêts denses et alpages immenses. Ce circuit remonte aux sources du pays d'Ax, bivouaque au-dessus de 2 000 m et gravit le Pic de Rulhe, toit de l'Ariège pyrénéenne.",
    etapes: [
      { jour: "J1", troncon: "Les Cabannes → Plateau de Beille → Étang du Guzet", km: "15 km", deni: "+1 200/−200 m", bivouac: "Étang du Guzet (1 800 m)" },
      { jour: "J2", troncon: "Guzet → Montée Pic de Rulhe → Haute Ariège", km: "16 km", deni: "+1 000/−850 m", bivouac: "Plateau haute Ariège (2 100 m)" },
      { jour: "J3", troncon: "Retour Les Cabannes par GR 10", km: "14 km", deni: "+400/−1 550 m", bivouac: "Retour au point de départ" },
    ],
    tips: [
      "L'Ariège est moins fréquentée que les Pyrénées béarnaises — vraie solitude garantie.",
      "Présence de loups dans la région — conservez vos aliments dans des sacs hermétiques.",
      "Les Cabannes est accessible en train depuis Toulouse — beau départ sans voiture.",
    ],
    links: [
      { icon: "🗺️", label: "Pyrénées Ariégeoises", url: "https://www.ariegepyrenees.com/randonnees", note: "Topos + infos" },
      { icon: "📷", label: "Altituderando – Ariège", url: "https://www.altituderando.com/Ariege", note: "Fiches détaillées" },
    ],
    highlights: ["Ariège sauvage et peu fréquentée", "Pic de Rulhe (2 783 m)", "Accessible en train"],
  },

  {
    id: 31, slug: "tour-balaïtous",
    emoji: "🦎", title: "Tour du Balaïtous – Lacs de Bramatuouère",
    region: "Vallée d'Azun (65)", zone: "pyrenees",
    level: "modere", levelLabel: "Modéré+", levelColor: "#e9c46a",
    jours: 3, kmJour: 14, totalKm: 42, denivelé: 2900,
    saison: "Juillet – mi-septembre",
    img: "https://images.unsplash.com/photo-1486870591958-9b9d0d1dda99?w=1200&q=85",
    imgThumb: "https://images.unsplash.com/photo-1486870591958-9b9d0d1dda99?w=600&q=75",
    depart: "Arrens-Marsous (65400) — parking maison du parc",
    acces: "Depuis Tarbes : 55 min · Depuis Pau : 1h15",
    sommet: "Col d'Arremoulit (2 448 m)",
    balisage: "GR 10 + HRP · Cairns sur crêtes",
    eau: "Lacs de Bramatuouère, lac d'Arremoulit",
    ravito: "Refuge d'Arremoulit (gardé en été)",
    carte: "IGN Top 25 · 1647 OT",
    description: "Le Balaïtous (3 144 m) est l'un des 4 000 m les plus sauvages des Pyrénées. On en fait le tour sans l'escalader, par des lacs glaciaires extraordinaires. Le col d'Arremoulit, passage obligé, donne l'impression d'entrer dans un autre monde — granitique, austère et grandiose.",
    etapes: [
      { jour: "J1", troncon: "Arrens → Lac d'Estaing → Lac du Tech", km: "13 km", deni: "+900/−200 m", bivouac: "Lac du Tech (1 680 m) — cadre boisé" },
      { jour: "J2", troncon: "Lac du Tech → Col d'Arremoulit → Lacs de Bramatuouère", km: "14 km", deni: "+1 100/−850 m", bivouac: "Lacs de Bramatuouère (2 300 m)" },
      { jour: "J3", troncon: "Bramatuouère → Vallée du gave d'Arrens → Arrens", km: "15 km", deni: "+900/−1 950 m", bivouac: "Retour au point de départ" },
    ],
    tips: [
      "Le col d'Arremoulit peut être enneigé jusqu'en juillet — vérifiez les conditions.",
      "Le refuge d'Arremoulit propose repas et ravitaillement si besoin.",
      "Les lacs de Bramatuouère sont parmi les plus beaux des Pyrénées — peu connus du grand public.",
    ],
    links: [
      { icon: "⛺", label: "Refuge d'Arremoulit", url: "https://www.refuge-arremoulit.com", note: "Gardé juillet-août" },
      { icon: "🏞️", label: "Parc National Pyrénées", url: "https://www.pyrenees-parcnational.fr/fr/des-decouvertes/randonnees", note: "Topos officiels" },
      { icon: "📷", label: "Altituderando – Balaïtous", url: "https://www.altituderando.com/Balaitous", note: "Fiches + photos" },
    ],
    highlights: ["Lacs de Bramatuouère (joyau caché)", "Col d'Arremoulit (2 448 m)", "Balaïtous en toile de fond"],
  },

  // ──────────────────────────────────────────────────────────
  // ★ DIFFICILE — RANDONNEURS EXPÉRIMENTÉS
  // ──────────────────────────────────────────────────────────

  {
    id: 6, slug: "hrp-ossoue-vignemale",
    emoji: "⛰️", title: "Boucle HRP Ossoue – Vignemale",
    region: "Pyrénées centrales (65)", zone: "pyrenees",
    level: "difficile", levelLabel: "Difficile", levelColor: "#c96a1e",
    jours: 4, kmJour: 17, totalKm: 68, denivelé: 4200,
    saison: "Juillet – septembre",
    img: "https://images.unsplash.com/photo-1464822759023-fed622ff2c3b?w=1200&q=85",
    imgThumb: "https://images.unsplash.com/photo-1464822759023-fed622ff2c3b?w=600&q=75",
    depart: "Pont d'Espagne, Cauterets (65110) — parking payant",
    acces: "Depuis Tarbes : 1h · Depuis Pau : 1h30",
    sommet: "Hourquette d'Ossoue (2 734 m)",
    balisage: "HRP jaune/rouge + GR 10",
    eau: "Nombreux lacs · Refuge Baysellance (gardé)",
    ravito: "Refuges des Oulettes + Baysellance",
    carte: "IGN Top 25 · 1748 OT",
    description: "L'itinéraire de la Haute Randonnée Pyrénéenne dans sa version la plus sauvage. Le Vignemale (3 298 m) en toile de fond, des lacs glaciaires à perte de vue, et le Refuge de Baysellance, le plus haut refuge gardé de France.",
    etapes: [
      { jour: "J1", troncon: "Pont d'Espagne → Lac de Gaube → Refuge des Oulettes", km: "14 km", deni: "+1 200/−100 m", bivouac: "Refuge des Oulettes (2 151 m)" },
      { jour: "J2", troncon: "Oulettes → Hourquette d'Ossoue → Refuge de Baysellance", km: "12 km", deni: "+1 050/−600 m", bivouac: "Refuge Baysellance (2 651 m)" },
      { jour: "J3", troncon: "Baysellance → Barrage d'Ossoue → Gavarnie", km: "24 km", deni: "+600/−1 900 m", bivouac: "Zone bivouac Gavarnie (1 600 m)" },
      { jour: "J4", troncon: "Gavarnie → Col des Tentes → Pont d'Espagne", km: "18 km", deni: "+1 350/−1 600 m", bivouac: "Retour au point de départ" },
    ],
    tips: [
      "Réservez les refuges au minimum 4 semaines à l'avance en juillet-août.",
      "La Hourquette d'Ossoue peut être enneigée jusqu'en juillet — crampons légers utiles.",
      "Nuits en altitude : prévoyez des vêtements chauds, même en été.",
    ],
    links: [
      { icon: "⛺", label: "Refuge des Oulettes", url: "https://refugedesoulettes.ffcam.fr", note: "Réservation obligatoire" },
      { icon: "⛺", label: "Refuge de Baysellance", url: "https://www.refuges-pyrenees.com/refuge-baysellance", note: "Plus haut refuge de France" },
      { icon: "🏞️", label: "Parc National Pyrénées", url: "https://www.pyrenees-parcnational.fr", note: "Règles bivouac" },
    ],
    highlights: ["Vignemale en toile de fond", "Refuge Baysellance (2 651 m)", "Cirque de Gavarnie"],
  },

  {
    id: 8, slug: "cerdagne-carlit",
    emoji: "🌞", title: "Boucle Cerdagne – Pic Carlit",
    region: "Pyrénées orientales (66)", zone: "orientales",
    level: "difficile", levelLabel: "Difficile", levelColor: "#c96a1e",
    jours: 5, kmJour: 18, totalKm: 90, denivelé: 5500,
    saison: "Juillet – mi-septembre",
    img: "https://images.unsplash.com/photo-1519681393784-d120267933ba?w=1200&q=85",
    imgThumb: "https://images.unsplash.com/photo-1519681393784-d120267933ba?w=600&q=75",
    depart: "Les Angles (66210) — parking lac des Bouillouses",
    acces: "Depuis Perpignan : 1h45 · Depuis Toulouse : 2h30",
    sommet: "Pic Carlit (2 921 m) — toit des Pyrénées orientales",
    balisage: "GR 10 + sentiers RNR Carlit",
    eau: "Nombreux lacs, Lac des Bouillouses",
    ravito: "Gîte des Bouillouses au départ",
    carte: "IGN Top 25 · 2249 ET",
    description: "La Cerdagne, pays du soleil. 5 jours dans le plus grand espace lacustre des Pyrénées, couronnés par l'ascension du Pic Carlit (2 921 m). Lacs, tourbières, crêtes frontière et lumière dorée de la montagne catalane.",
    etapes: [
      { jour: "J1", troncon: "Bouillouses → Tour du lac → Lac du Campcardos", km: "16 km", deni: "+900/−500 m", bivouac: "Lac du Campcardos (2 310 m)" },
      { jour: "J2", troncon: "Campcardos → Portella de Mantet → Mantet", km: "20 km", deni: "+1 200/−1 050 m", bivouac: "Zone bivouac Mantet (1 700 m)" },
      { jour: "J3", troncon: "Mantet → Col de la Comassa → Lac de Lanós", km: "18 km", deni: "+1 050/−900 m", bivouac: "Lac de Lanós (2 213 m)" },
      { jour: "J4", troncon: "Lac de Lanós → Ascension Pic Carlit → Bouillouses", km: "20 km", deni: "+1 550/−1 500 m", bivouac: "Lac des Bouillouses (2 017 m)" },
      { jour: "J5", troncon: "Tour final Bouillouses → Les Angles", km: "16 km", deni: "+800/−900 m", bivouac: "Retour au point de départ" },
    ],
    tips: [
      "La Cerdagne est l'une des régions les plus ensoleillées de France — protection solaire obligatoire.",
      "Les Bouillouses sont accessibles en navette depuis Les Angles en juillet-août.",
      "Orages fréquents l'après-midi : partez tôt pour les crêtes.",
    ],
    links: [
      { icon: "🌿", label: "RNN Carlit", url: "https://www.reserves-naturelles.org/carlit", note: "Réglementation + faune" },
      { icon: "🏠", label: "Gîte des Bouillouses", url: "https://www.bouillouses.fr", note: "Hébergement départ" },
      { icon: "🗺️", label: "Pyrénées Catalanes", url: "https://www.pyrenees-catalanes.fr", note: "Infos régionales" },
    ],
    highlights: ["Pic Carlit (2 921 m)", "Cerdagne — pays du soleil", "Espace lacustre unique"],
  },

  {
    id: 9, slug: "midi-ossau-espagne",
    emoji: "🏔️", title: "Grand Tour du Midi d'Ossau",
    region: "Béarn / Aragon (64 · ES)", zone: "pyrenees",
    level: "difficile", levelLabel: "Difficile", levelColor: "#c96a1e",
    jours: 4, kmJour: 15, totalKm: 62, denivelé: 3800,
    saison: "Juillet – septembre",
    img: "https://images.unsplash.com/photo-1486870591958-9b9d0d1dda99?w=1200&q=85",
    imgThumb: "https://images.unsplash.com/photo-1486870591958-9b9d0d1dda99?w=600&q=75",
    depart: "Gabas (64440) — parking lac de Bious-Artigues",
    acces: "Depuis Pau : 1h15 · Depuis Bayonne : 1h45",
    sommet: "Col d'Ayous (2 185 m) + passage en Espagne",
    balisage: "GR 10 France + GR 11 Espagne",
    eau: "Refuges Pombie, Respomuso + sources altitude",
    ravito: "Refuge de Pombie (Espagne) — repas disponibles",
    carte: "IGN 1547 OT + Editorial Alpina n°25",
    description: "Le tour du Pic du Midi d'Ossau (2 884 m) est le circuit de référence des Pyrénées béarnaises. On franchit la frontière franco-espagnole, on bivouaque côté Aragon, et on tourne autour du géant en admirant ses faces nord et sud.",
    etapes: [
      { jour: "J1", troncon: "Bious-Artigues → Col d'Ayous → Refuge d'Ayous → Portalet", km: "16 km", deni: "+1 200/−600 m", bivouac: "Refuge d'Ayous (2 185 m)" },
      { jour: "J2", troncon: "Portalet → Refuge de Pombie (versant espagnol)", km: "15 km", deni: "+950/−850 m", bivouac: "Refuge de Pombie (2 040 m)" },
      { jour: "J3", troncon: "Pombie → Col de Peyreget → Tour versant sud → Lac de Peyreget", km: "17 km", deni: "+1 100/−1 000 m", bivouac: "Lac de Peyreget (2 000 m)" },
      { jour: "J4", troncon: "Lac de Peyreget → Col Long de Magnabaigt → Bious-Artigues", km: "14 km", deni: "+550/−1 350 m", bivouac: "Retour au point de départ" },
    ],
    tips: [
      "Passage en Espagne (J2) : aucune formalité pour les citoyens européens.",
      "Le Refuge de Pombie propose repas et ravitaillement — idéal pour alléger le sac.",
      "Les vautours fauves survolent en permanence cette zone — spectacle garanti !",
    ],
    links: [
      { icon: "⛺", label: "Refuge d'Ayous", url: "https://www.refuge-ayous.com", note: "Réservation en ligne" },
      { icon: "⛺", label: "Refugio de Pombie", url: "https://www.refugiodepombie.com", note: "Côté Aragon" },
      { icon: "📷", label: "Altituderando – Midi Ossau", url: "https://www.altituderando.com/Tour-du-Pic-du-Midi-d-Ossau", note: "Description complète" },
    ],
    highlights: ["Traversée France-Espagne", "Autour du Midi d'Ossau (2 884 m)", "Vautours fauves"],
  },

  {
    id: 32, slug: "massif-du-canigou",
    emoji: "🔥", title: "Tour du Canigou – Montagne Sacrée",
    region: "Pyrénées-Orientales (66)", zone: "orientales",
    level: "difficile", levelLabel: "Difficile", levelColor: "#c96a1e",
    jours: 4, kmJour: 16, totalKm: 64, denivelé: 4400,
    saison: "Juin – octobre",
    img: "https://images.unsplash.com/photo-1464822759023-fed622ff2c3b?w=1200&q=85",
    imgThumb: "https://images.unsplash.com/photo-1464822759023-fed622ff2c3b?w=600&q=75",
    depart: "Vernet-les-Bains (66820) — parking village",
    acces: "Depuis Perpignan : 55 min · Depuis Barcelona : 2h",
    sommet: "Pic du Canigou (2 784 m) — montagne sacrée des Catalans",
    balisage: "GR 10 + sentiers PR locaux — balisage jaune",
    eau: "Sources en forêt, rares au-dessus de 1 800 m",
    ravito: "Chalet-Hôtel des Cortalets (gardé, repas)",
    carte: "IGN Top 25 · 2349 ET",
    description: "Le Canigou est la montagne sacrée des Catalans, visible depuis la mer à 100 km. Son tour de 4 jours mêle forêts de pins noirs, gorges sauvages du Llech, villages romans et sommet mythique. La nuit au Chalet des Cortalets, sous les étoiles méditerranéennes, est inoubliable.",
    etapes: [
      { jour: "J1", troncon: "Vernet → Gorges du Llech → Refuge de Mariailles", km: "16 km", deni: "+1 300/−100 m", bivouac: "Refuge de Mariailles (1 718 m)" },
      { jour: "J2", troncon: "Mariailles → Sommet Canigou → Chalet des Cortalets", km: "14 km", deni: "+1 300/−850 m", bivouac: "Chalet des Cortalets (2 150 m)" },
      { jour: "J3", troncon: "Cortalets → Forêt de sapins → Col de Jou", km: "17 km", deni: "+650/−1 300 m", bivouac: "Col de Jou (1 124 m) — forêt" },
      { jour: "J4", troncon: "Col de Jou → Vernet-les-Bains", km: "17 km", deni: "+1 150/−1 900 m", bivouac: "Retour au point de départ" },
    ],
    tips: [
      "L'ascension du Canigou depuis les Cortalets est incontournable — 2h aller/retour.",
      "La fête de la Saint-Jean (24 juin) sur le Canigou est un événement populaire catalan.",
      "Vernet-les-Bains est une belle ville thermale — idéale pour récupérer après le circuit.",
    ],
    links: [
      { icon: "⛺", label: "Refuge de Mariailles", url: "https://www.refuge-mariailles.com", note: "Gardé mai-octobre" },
      { icon: "🏔️", label: "Chalet des Cortalets", url: "https://www.chalet-cortalets.com", note: "Repas + dortoirs" },
      { icon: "📷", label: "Altituderando – Canigou", url: "https://www.altituderando.com/Canigou", note: "Fiches + photos" },
    ],
    highlights: ["Montagne sacrée des Catalans", "Gorges du Llech", "Vue sur la Méditerranée"],
  },

  {
    id: 33, slug: "haute-route-pyrenees-basque",
    emoji: "🌊", title: "Traversée Pays Basque – Haute Route",
    region: "Pays Basque + Béarn (64)", zone: "paysbasque",
    level: "difficile", levelLabel: "Difficile", levelColor: "#c96a1e",
    jours: 5, kmJour: 18, totalKm: 90, denivelé: 5200,
    saison: "Mai – octobre",
    img: "https://images.unsplash.com/photo-1509316785289-025f5b846b35?w=1200&q=85",
    imgThumb: "https://images.unsplash.com/photo-1509316785289-025f5b846b35?w=600&q=75",
    depart: "Hendaye (64700) — gare ou parking bord de mer",
    acces: "Depuis Bayonne : 45 min · TGV direct depuis Paris",
    sommet: "La Rhune (905 m) + Pic d'Orhy (2 017 m)",
    balisage: "GR 10 rouge/blanc intégral",
    eau: "Villages basques nombreux, sources sur crêtes",
    ravito: "Villages : Sare, Ainhoa, Saint-Jean-Pied-de-Port",
    carte: "IGN Top 25 · 1345 OT + 1346 OT",
    description: "La traversée du Pays Basque de la mer à la montagne, du Golfe de Gascogne aux premiers 2 000 m pyrénéens. 5 jours sur le GR 10, du littoral basque aux hauteurs de la frontière navarro-béarnaise. Villages emblématiques, crêtes pelouses, fromages de brebis et txakoli au retour.",
    etapes: [
      { jour: "J1", troncon: "Hendaye → Col d'Ibardin → La Rhune → Sare", km: "18 km", deni: "+1 100/−1 050 m", bivouac: "Sare (170 m) — prairie" },
      { jour: "J2", troncon: "Sare → Ainhoa → Col d'Urdazuri → Bidarray", km: "20 km", deni: "+950/−900 m", bivouac: "Crête d'Iparla (1 000 m)" },
      { jour: "J3", troncon: "Bidarray → Saint-Étienne-de-Baïgorry → Col d'Arnostéguy", km: "18 km", deni: "+1 100/−950 m", bivouac: "Plateau d'Arnostéguy (1 200 m)" },
      { jour: "J4", troncon: "Arnostéguy → Saint-Jean-Pied-de-Port → Col de Bentarte", km: "19 km", deni: "+1 000/−850 m", bivouac: "Forêt de Haute-Navarre (900 m)" },
      { jour: "J5", troncon: "Bentarte → Pic d'Orhy → Larrau", km: "15 km", deni: "+1 050/−1 450 m", bivouac: "Retour par navette ou bus" },
    ],
    tips: [
      "Point de départ idéal : train depuis Paris ou Bayonne jusqu'à Hendaye.",
      "Chaque soir, vous pouvez choisir d'aller dormir en gîte — pratique pour alléger le sac.",
      "Le Pays Basque reste vert même en été — moins de problèmes d'eau qu'en Pyrénées centrales.",
    ],
    links: [
      { icon: "🗺️", label: "GR 10 – FFRandonnée", url: "https://www.ffrandonnee.fr/randonnee/gr10", note: "Topoguide officiel" },
      { icon: "📷", label: "Rando Pays Basque", url: "https://rando-pays-basque.info/gr10-pays-basque/", note: "Étapes détaillées" },
      { icon: "🌤️", label: "Météo Pyrénées", url: "https://meteofrance.com/meteo-montagne/pyrenees", note: "Prévisions" },
    ],
    highlights: ["De la mer à la montagne", "GR 10 intégral", "Villages basques et fromages"],
  },

  {
    id: 34, slug: "traversee-encantats-espagne",
    emoji: "✨", title: "Els Encantats – Parc Aigüestortes",
    region: "Catalogne (Espagne · 1h de la 66)", zone: "orientales",
    level: "difficile", levelLabel: "Difficile", levelColor: "#c96a1e",
    jours: 4, kmJour: 14, totalKm: 56, denivelé: 3600,
    saison: "Juillet – mi-septembre",
    img: "https://images.unsplash.com/photo-1506905925346-21bda4d32df4?w=1200&q=85",
    imgThumb: "https://images.unsplash.com/photo-1506905925346-21bda4d32df4?w=600&q=75",
    depart: "Espot (Lleida, Espagne) — 1h depuis Font Romeu",
    acces: "Depuis Font-Romeu : 1h · Depuis Perpignan : 2h30",
    sommet: "Pic de Peguera (2 982 m)",
    balisage: "Sentiers GR 11 + sentiers Parc Nacional",
    eau: "Centaines de lacs glaciaires",
    ravito: "Refuges Estany Llong, Ernest Mallafré",
    carte: "Editorial Alpina — Aigüestortes 1:25000",
    description: "Le Parc Nacional d'Aigüestortes i Estany de Sant Maurici est le plus beau parc national espagnol. Centaines de lacs, sommets de granite, forêts de pins à crochets — un cirque naturel extraordinaire à 2h des Pyrénées françaises. Les Encantats, aiguilles jumelles de 2 746 m, veillent sur ce paradis.",
    etapes: [
      { jour: "J1", troncon: "Espot → Estany de Sant Maurici → Refugi Ernest Mallafré", km: "12 km", deni: "+800/−100 m", bivouac: "Refugi Ernest Mallafré (2 030 m)" },
      { jour: "J2", troncon: "Mallafré → Estanys de Ratera → Amitges → Pic de Peguera", km: "15 km", deni: "+1 200/−900 m", bivouac: "Refugi d'Amitges (2 380 m)" },
      { jour: "J3", troncon: "Amitges → Estany Llong → Refugi Estany Llong", km: "14 km", deni: "+700/−900 m", bivouac: "Refugi Estany Llong (2 000 m)" },
      { jour: "J4", troncon: "Estany Llong → Cavallers → Retour Espot en 4x4 taxi", km: "15 km", deni: "+600/−1 400 m", bivouac: "Retour au point de départ" },
    ],
    tips: [
      "Le bivouac est interdit dans le cœur du parc espagnol — dormez impérativement dans les refuges.",
      "Les taxis 4x4 sont indispensables pour rejoindre certains secteurs — réservez à l'avance.",
      "Emportez un peu d'espagnol ou catalan — les refuges ne parlent pas toujours français.",
    ],
    links: [
      { icon: "🏞️", label: "Parc Nacional Aigüestortes", url: "https://parcsnaturals.gencat.cat/ca/aiguestortes", note: "Réglementation officielle" },
      { icon: "⛺", label: "Refugis CAE", url: "https://www.feec.cat/refugis", note: "Réservations refuges catalans" },
      { icon: "📍", label: "AllTrails – Aigüestortes", url: "https://www.alltrails.com/parks/spain/catalonia/parc-nacional-d-aiguastortes-i-estany-de-sant-maurici", note: "Traces GPS" },
    ],
    highlights: ["Parc national espagnol le plus beau", "Centaines de lacs glaciaires", "Les Encantats (aiguilles jumelles)"],
  },

  // ──────────────────────────────────────────────────────────
  // ★ EXPERT — ALPINISTES & ULTRA-RANDONNEURS
  // ──────────────────────────────────────────────────────────

  {
    id: 35, slug: "hrp-integrale-est",
    emoji: "💀", title: "HRP – Haute Route Pyrénéenne (section Est)",
    region: "Pyrénées centrales & orientales", zone: "pyrenees",
    level: "expert", levelLabel: "Expert", levelColor: "#8B0000",
    jours: 12, kmJour: 22, totalKm: 265, denivelé: 18000,
    saison: "Juillet – mi-août seulement",
    img: "https://images.unsplash.com/photo-1519681393784-d120267933ba?w=1200&q=85",
    imgThumb: "https://images.unsplash.com/photo-1519681393784-d120267933ba?w=600&q=75",
    depart: "Gavarnie (65120)",
    acces: "Depuis Tarbes : 1h30",
    sommet: "Brèche de Roland (2 807 m) + nombreux cols >2 500 m",
    balisage: "HRP balisage minimal — lecture de carte + GPS indispensable",
    eau: "Variable — portez 3L minimum entre les sources",
    ravito: "Refuges essentiel — planification minutieuse requise",
    carte: "3 cartes IGN Top 25 + Rando Editions guide HRP",
    description: "La section Est de la Haute Route Pyrénéenne, de Gavarnie aux Bouillouses. Douze jours de haute montagne pyrénéenne, souvent hors sentier, avec des passages en crampons possibles. Réservé aux randonneurs très expérimentés ayant déjà plusieurs séjours en altitude. L'aventure pyrénéenne ultime.",
    etapes: [
      { jour: "J1-2", troncon: "Gavarnie → Brèche de Roland → Ordesa (Espagne)", km: "44 km", deni: "+2 800/−2 600 m", bivouac: "Cirque d'Ordesa (1 900 m)" },
      { jour: "J3-4", troncon: "Ordesa → Col de la Sausse → Lac d'Aygues-Tortes", km: "42 km", deni: "+3 200/−3 000 m", bivouac: "Lac d'Aygues-Tortes (2 400 m)" },
      { jour: "J5-7", troncon: "Aygues-Tortes → Col de la Pez → Estours → Andorre", km: "68 km", deni: "+5 400/−5 100 m", bivouac: "Secteur Andorre (2 000 m)" },
      { jour: "J8-10", troncon: "Andorre → Carlit → Cerdagne", km: "66 km", deni: "+4 800/−4 600 m", bivouac: "Lac des Bouillouses (2 017 m)" },
      { jour: "J11-12", troncon: "Cerdagne → Pic Carlit → Les Angles", km: "45 km", deni: "+2 800/−3 700 m", bivouac: "Retour aux Angles" },
    ],
    tips: [
      "Ne tentez cette section qu'avec une expérience confirmée en navigation hors sentier.",
      "Prévoir un plan de sortie chaque jour — conditions météo décisives.",
      "Emportez crampons légers et piolet de marche en juillet si fonds neigeux.",
      "Guide de référence : 'La Haute Route Pyrénéenne' de R. Ollivier (Rando Editions).",
    ],
    links: [
      { icon: "📖", label: "Guide HRP Rando Editions", url: "https://www.rando-editions.com/haute-route-pyreneenne", note: "Topo de référence" },
      { icon: "🏞️", label: "Parc National Pyrénées", url: "https://www.pyrenees-parcnational.fr", note: "Réglementations" },
      { icon: "🗺️", label: "HRP sur Wikiloc", url: "https://fr.wikiloc.com/itineraires/hrp-haute-route-pyreneenne", note: "Traces GPS communautaires" },
    ],
    highlights: ["12 jours de haute montagne", "Passages hors sentier", "Réservé experts confirmés"],
  },

  {
    id: 36, slug: "ascension-vignemale",
    emoji: "🧊", title: "Ascension du Vignemale (3 298 m)",
    region: "Pyrénées centrales (65)", zone: "pyrenees",
    level: "expert", levelLabel: "Expert", levelColor: "#8B0000",
    jours: 2, kmJour: 16, totalKm: 32, denivelé: 2200,
    saison: "Juillet – mi-septembre",
    img: "https://images.unsplash.com/photo-1464822759023-fed622ff2c3b?w=1200&q=85",
    imgThumb: "https://images.unsplash.com/photo-1464822759023-fed622ff2c3b?w=600&q=75",
    depart: "Pont d'Espagne, Cauterets (65110)",
    acces: "Depuis Tarbes : 1h · Depuis Pau : 1h30",
    sommet: "Vignemale (3 298 m) — point culminant des Pyrénées françaises",
    balisage: "GR 10 jusqu'au refuge · Glacier + rocher non balisé — progression alpinisme PD",
    eau: "Refuge des Oulettes, Refuge de Baysellance",
    ravito: "Refuge Baysellance (le plus haut gardé de France à 2 651 m)",
    carte: "IGN Top 25 · 1748 OT",
    description: "Le Vignemale (3 298 m) est le toit des Pyrénées françaises. Son ascension par le glacier d'Ossoue (voie normale) est une véritable course de haute montagne : crampons et piolet obligatoires, progression sur glacier. Une nuit au Refuge Baysellance à 2 651 m, puis l'aube sur le sommet — l'expérience ultime.",
    etapes: [
      { jour: "J1", troncon: "Pont d'Espagne → Refuge des Oulettes → Refuge Baysellance", km: "16 km", deni: "+1 900/−150 m", bivouac: "Refuge Baysellance (2 651 m)" },
      { jour: "J2", troncon: "Baysellance → Glacier d'Ossoue → Vignemale (3 298 m) → Retour Pont d'Espagne", km: "16 km", deni: "+650/−2 500 m", bivouac: "Retour au point de départ" },
    ],
    tips: [
      "Crampons 10 pointes + piolet + corde indispensables — montée sur glacier (45°).",
      "Partez du refuge avant 5h pour atteindre le sommet avant les orages d'après-midi.",
      "Stage initiation alpinisme fortement recommandé avant cette ascension.",
      "Le glacier d'Ossoue recule chaque année — vérifiez les conditions auprès du refuge.",
    ],
    links: [
      { icon: "⛺", label: "Refuge Baysellance", url: "https://www.refuges-pyrenees.com/refuge-baysellance", note: "Réservation obligatoire" },
      { icon: "🧊", label: "Info glacier Vignemale", url: "https://www.altituderando.com/Le-Vignemale-par-le-glacier-d-Ossoue", note: "Conditions + photos" },
      { icon: "🏔️", label: "FFME Alpinisme", url: "https://www.ffme.fr/formation-alpinisme", note: "Formations initiation" },
    ],
    highlights: ["Toit des Pyrénées françaises (3 298 m)", "Glacier d'Ossoue", "Refuge le plus haut de France"],
  },

  {
    id: 37, slug: "traverse-pyreneenne-10j",
    emoji: "🗺️", title: "Grande Traversée Pyrénéenne — 10 jours",
    region: "Océan Atlantique → Méditerranée", zone: "pyrenees",
    level: "expert", levelLabel: "Expert", levelColor: "#8B0000",
    jours: 10, kmJour: 25, totalKm: 250, denivelé: 15000,
    saison: "Juillet – début août seulement",
    img: "https://images.unsplash.com/photo-1509316785289-025f5b846b35?w=1200&q=85",
    imgThumb: "https://images.unsplash.com/photo-1509316785289-025f5b846b35?w=600&q=75",
    depart: "Hendaye (64700) — bord de mer",
    acces: "Depuis Bayonne : 45 min TGV",
    sommet: "Vignemale (3 298 m) + Brèche de Roland + Pic d'Aneto (3 404 m, côté ES)",
    balisage: "GR 10 principal + variantes HRP",
    eau: "Planification rigoureuse — voir topo par étape",
    ravito: "Ravitaillements programmés à : Saint-Jean-Pied-de-Port, Cauterets, Gavarnie, Foix",
    carte: "Collection complète 8 cartes IGN 1:25000",
    description: "La traversée complète des Pyrénées de l'Atlantique à la Méditerranée en 10 jours est le défi ultime pour les coureurs de montagne et ultra-randonneurs. Cette version accélérée du GR 10 / HRP n'est pas une rando — c'est une expédition. Pour ceux qui ont déjà plusieurs traversées de massifs à leur actif.",
    etapes: [
      { jour: "J1-2", troncon: "Hendaye → La Rhune → Bidarray → Saint-Jean-Pied-de-Port", km: "50 km", deni: "+2 800/−2 700 m", bivouac: "Saint-Jean-Pied-de-Port" },
      { jour: "J3-4", troncon: "Saint-Jean → Larrau → Arette → Lescun", km: "55 km", deni: "+3 500/−3 400 m", bivouac: "Lescun (900 m)" },
      { jour: "J5-6", troncon: "Lescun → Ossau → Cauterets", km: "58 km", deni: "+4 200/−4 100 m", bivouac: "Cauterets (1 000 m)" },
      { jour: "J7-8", troncon: "Cauterets → Vignemale → Gavarnie → Ordesa", km: "52 km", deni: "+4 000/−3 900 m", bivouac: "Ordesa (Espagne)" },
      { jour: "J9-10", troncon: "Ordesa → Andorre → Pic Carlit → Banyuls-sur-Mer", km: "85 km", deni: "+5 500/−6 900 m", bivouac: "Banyuls-sur-Mer (mer !)" },
    ],
    tips: [
      "Ce format 10 jours requiert des journées de 8–10h de marche effectives à 4 km/h de moyenne.",
      "Préparez 6 mois à l'avance : sorties longues chaque weekend + sortie bivouac mensuelle.",
      "Rejoignez le groupe Facebook 'GR10 Traversée Pyrénées' pour les retours d'expérience.",
      "Budget estimé : 400–600€ (refuges, navettes, ravitaillement).",
    ],
    links: [
      { icon: "📖", label: "Topoguide GR 10 FFR", url: "https://www.ffrandonnee.fr/randonnee/gr10", note: "Guide officiel en librairie" },
      { icon: "🗺️", label: "GR10 sur Wikiloc", url: "https://fr.wikiloc.com/itineraires/gr10-pyrenees", note: "Traces GPS intégrales" },
      { icon: "📱", label: "Application Komoot", url: "https://www.komoot.com", note: "Navigation hors ligne" },
    ],
    highlights: ["Atlantique → Méditerranée", "10 jours non-stop", "Vignemale + Brèche de Roland"],
  },

  // ──────────────────────────────────────────────────────────
  // ★ BONUS — CIRCUITS THÉMATIQUES ET SPÉCIAUX
  // ──────────────────────────────────────────────────────────

  {
    id: 38, slug: "circuit-lacs-ariege",
    emoji: "🌙", title: "Lacs Glaciaires d'Ariège – Étangs de Bassiès",
    region: "Ariège (09)", zone: "ariege",
    level: "modere", levelLabel: "Modéré", levelColor: "#e9c46a",
    jours: 3, kmJour: 12, totalKm: 36, denivelé: 2200,
    saison: "Juillet – septembre",
    img: "https://images.unsplash.com/photo-1501854140801-50d01698950b?w=1200&q=85",
    imgThumb: "https://images.unsplash.com/photo-1501854140801-50d01698950b?w=600&q=75",
    depart: "Auzat (09220) — parking du Moulin",
    acces: "Depuis Tarascon-sur-Ariège : 20 min · Depuis Foix : 50 min",
    sommet: "Pic de Tristagne (2 878 m) — optionnel",
    balisage: "GR 10 + sentiers PR locaux bien balisés",
    eau: "Abondante : lacs des Besines, de Roumazet, étangs de Bassiès",
    ravito: "Aucun en chemin · Auzat pour provisions",
    carte: "IGN Top 25 · 2148 OT",
    description: "Les étangs de Bassiès, chapelet de lacs glaciaires lovés dans un cirque granitique de l'Ariège, constituent l'un des plus beaux trésors des Pyrénées centrales. Peu connus, peu fréquentés — les isards et les marmottes sont vos principaux compagnons.",
    etapes: [
      { jour: "J1", troncon: "Auzat → Vallée de Siguer → Lac des Besines", km: "12 km", deni: "+900/−100 m", bivouac: "Lac des Besines (2 104 m)" },
      { jour: "J2", troncon: "Lac des Besines → Col de la Sierpe → Étangs de Bassiès", km: "13 km", deni: "+800/−750 m", bivouac: "Étangs de Bassiès (2 170 m)" },
      { jour: "J3", troncon: "Bassiès → Vallée du Vicdessos → Auzat", km: "11 km", deni: "+500/−1 350 m", bivouac: "Retour au point de départ" },
    ],
    tips: [
      "Les étangs de Bassiès sont l'une des destinations les plus secrètes des Pyrénées.",
      "Marmottes garanties dès l'entrée dans la vallée de Siguer.",
      "Eau partout — filtre recommandé mais les lacs sont cristallins.",
    ],
    links: [
      { icon: "🗺️", label: "Pyrénées Ariégeoises", url: "https://www.ariegepyrenees.com/randonnees", note: "Topos officiels" },
      { icon: "📷", label: "Altituderando – Bassiès", url: "https://www.altituderando.com/Etangs-de-Bassies", note: "Photos + fiche" },
    ],
    highlights: ["Étangs de Bassiès (joyau secret)", "Isards et marmottes", "Ariège quasi-déserte"],
  },

  {
    id: 39, slug: "andorre-tour",
    emoji: "🏳️", title: "Tour d'Andorre en Bivouac",
    region: "Andorre + frontières (66 · 09)", zone: "orientales",
    level: "difficile", levelLabel: "Difficile", levelColor: "#c96a1e",
    jours: 5, kmJour: 16, totalKm: 80, denivelé: 5000,
    saison: "Juillet – mi-septembre",
    img: "https://images.unsplash.com/photo-1509316785289-025f5b846b35?w=1200&q=85",
    imgThumb: "https://images.unsplash.com/photo-1509316785289-025f5b846b35?w=600&q=75",
    depart: "Pas de la Casa (Andorre) — accessible depuis Font-Romeu",
    acces: "Depuis Perpignan : 2h · Depuis Toulouse : 2h30",
    sommet: "Pic de Médecourbe (2 914 m)",
    balisage: "GR 11 Espagne + sentiers Andorre — GPS recommandé",
    eau: "Très abondante — rivières et lacs partout",
    ravito: "Andorre-la-Vieille (J2) — commerces duty-free",
    carte: "Carte touristique Andorre 1:40000",
    description: "Tour complet de la principauté d'Andorre par ses crêtes frontalières. Une curiosité géographique et une aventure unique : dormir dans 3 pays (France, Andorre, Espagne) en 5 jours. Les vallées andorranes, vierges de tourisme de masse en altitude, réservent de belles surprises.",
    etapes: [
      { jour: "J1", troncon: "Pas de la Casa → Coma Pedrosa → Lac de les Fonts", km: "16 km", deni: "+1 200/−800 m", bivouac: "Lac de les Fonts (2 400 m)" },
      { jour: "J2", troncon: "Lac de les Fonts → Andorre-la-Vieille → Canillo", km: "17 km", deni: "+400/−1 600 m", bivouac: "Canillo (1 531 m)" },
      { jour: "J3", troncon: "Canillo → Col de l'Ordino → Pic de la Casamanya", km: "15 km", deni: "+1 100/−750 m", bivouac: "Plateau sous Casamanya (2 200 m)" },
      { jour: "J4", troncon: "Casamanya → Frontière Espagne → Cerdagne", km: "17 km", deni: "+1 200/−1 400 m", bivouac: "Cerdagne espagnole (1 800 m)" },
      { jour: "J5", troncon: "Cerdagne → Pas de la Casa", km: "15 km", deni: "+1 100/−1 450 m", bivouac: "Retour au point de départ" },
    ],
    tips: [
      "Le bivouac en Andorre est toléré hors des zones protégées — respectez la discrétion.",
      "Andorre-la-Vieille (J2) permet de racheter du matériel ou du ravitaillement duty-free.",
      "Emportez carte SIM internationale — réseau variable selon les opérateurs.",
    ],
    links: [
      { icon: "🏳️", label: "Turisme d'Andorra", url: "https://www.visitandorra.com/fr/randonnees", note: "Topos + infos pratiques" },
      { icon: "🗺️", label: "GR 11 – Pyrenees", url: "https://www.gr11.net", note: "Trace GPS intégrale" },
    ],
    highlights: ["3 pays en 5 jours", "Andorre en haute altitude", "Ravitaillement duty-free"],
  },
];

// ── RANDOS JOURNÉE ──────────────────────────────────────────
const RANDOS_JOURNEE = [
  {
    id: 10, slug: "la-rhune-sare",
    emoji: "🚂", title: "La Rhune depuis Sare",
    region: "Labourd · Pays Basque", zone: "paysbasque",
    type: "journee", level: "modere", levelLabel: "Modéré",
    distance: "10 km", duree: "4h", denivelé: "800 m",
    distanceBayonne: "40 min de Bayonne",
    img: "https://images.unsplash.com/photo-1500534314209-a25ddb2bd429?w=800&q=80",
    description: "Sommet emblématique du Pays Basque (905 m), accessible via le GR 10 depuis Sare. Vue à 360° sur l'Atlantique, la côte basque et les Pyrénées. En bonus : le célèbre petit train à crémaillère centenaire.",
    depart: "Village de Sare — parking gratuit (43.304179, -1.594296)",
    balisage: "GR 10 rouge/blanc jusqu'au sommet",
    highlights: ["Vue 360° Atlantique + Pyrénées", "Petit train centenaire (option)", "Pottoks au sommet"],
    links: [
      { icon: "🗺️", label: "Topo Topopyrenees", url: "https://www.topopyrenees.com/la-rhune-905m-en-boucle-depuis-le-village-de-sare/" },
      { icon: "📍", label: "AllTrails", url: "https://www.alltrails.com/fr/randonnee/france/pyrenees-atlantiques/sare-la-rhune" },
      { icon: "🚂", label: "Train de la Rhune", url: "https://www.rhune.com/fr/infos-pratiques" },
    ],
  },
  {
    id: 11, slug: "mondarrain-ainhoa",
    emoji: "🐄", title: "Pic du Mondarrain depuis Ainhoa",
    region: "Labourd · Pays Basque", zone: "paysbasque",
    type: "journee", level: "modere", levelLabel: "Modéré",
    distance: "13,5 km", duree: "4h–5h", denivelé: "650 m",
    distanceBayonne: "35 min de Bayonne",
    img: "https://images.unsplash.com/photo-1441974231531-c6227db76b6e?w=800&q=80",
    description: "Le Mondarrain (749 m) depuis le plus beau village du Pays Basque. La montée passe par le chemin de croix d'Ainhoa, traverse des pâturages gardés par les Betizu (vaches sauvages classées Natura 2000), et offre une vue jusqu'à la mer.",
    depart: "Ainhoa (64250) — parking près de l'office de tourisme",
    balisage: "GR 10 + sentiers balisés jaune",
    highlights: ["Village classé + beau de France", "Vaches Betizu (Natura 2000)", "Panorama mer + montagnes"],
    links: [
      { icon: "🗺️", label: "Rando Pays Basque", url: "https://rando-pays-basque.info/le-mondarrain-depuis-ainhoa/" },
      { icon: "📍", label: "Visorando", url: "https://www.visorando.com/randonnee-mondarrain.html" },
    ],
  },
  {
    id: 12, slug: "mont-ursuya-hasparren",
    emoji: "🦅", title: "Mont Ursuya depuis Hasparren",
    region: "Labourd · Pays Basque", zone: "paysbasque",
    type: "journee", level: "modere", levelLabel: "Modéré",
    distance: "12,9 km", duree: "4h30–5h", denivelé: "566 m",
    distanceBayonne: "25 min de Bayonne",
    img: "https://images.unsplash.com/photo-1508739773434-c26b3d09e071?w=800&q=80",
    description: "Le Mont Ursuya (681 m), belvédère isolé du reste de la chaîne, domine les plaines basques et béarnaises. Par temps clair, vue jusqu'à l'Ossau et au Pic du Midi de Bigorre. La rando la plus proche de Bayonne !",
    depart: "Hasparren — quartier Zelhaia (parking fronton)",
    balisage: "PR local Bidegaraia — balisage jaune",
    highlights: ["25 min de Bayonne seulement", "Vue sur Béarn et Labourd", "Peu fréquenté, calme"],
    links: [
      { icon: "📷", label: "Altituderando", url: "https://www.altituderando.com/Ursuya-681m-par-Zelhaia-Hasparren" },
      { icon: "📍", label: "AllTrails", url: "https://www.alltrails.com/fr/randonnee/france/pyrenees-atlantiques/hasparren-mont-ursuya" },
    ],
  },
  {
    id: 13, slug: "corniche-basque",
    emoji: "🌊", title: "Corniche Basque – Sentier du Littoral",
    region: "Côte Basque", zone: "paysbasque",
    type: "journee", level: "facile", levelLabel: "Facile",
    distance: "15 km", duree: "5h–6h", denivelé: "400 m",
    distanceBayonne: "30 min de Bayonne",
    img: "https://images.unsplash.com/photo-1507525428034-b723cf961d3e?w=800&q=80",
    description: "De Bidart à Hendaye, 15 km de falaises sauvages et de panoramas sur l'Atlantique. Le sentier du littoral longe la côte basque encore préservée, entre calanques, criques cachées et vues sur les Pyrénées. Zéro altitude, 100% mer.",
    depart: "Bidart (64210) — parking de la plage du Centre",
    balisage: "GR 121 rouge/blanc — bien balisé",
    highlights: ["Falaises et criques sauvages", "Vue Pyrénées côté mer", "Faune marine"],
    links: [
      { icon: "🌊", label: "Guide du Pays Basque", url: "https://www.guide-du-paysbasque.com/fr/experiences/sportive/article-les-plus-belles-randonnees-du-pays-basque--131.html" },
      { icon: "📍", label: "AllTrails – Corniche", url: "https://www.alltrails.com/fr/randonnee/france/pyrenees-atlantiques/corniche-basque" },
    ],
  },
  {
    id: 14, slug: "pic-orhy",
    emoji: "🦌", title: "Pic d'Orhy (2 017 m) depuis Larrau",
    region: "Soule · Pays Basque", zone: "paysbasque",
    type: "journee", level: "modere", levelLabel: "Modéré",
    distance: "14 km", duree: "5h30", denivelé: "1 000 m",
    distanceBayonne: "1h30 de Bayonne",
    img: "https://images.unsplash.com/photo-1464822759023-fed622ff2c3b?w=800&q=80",
    description: "Le Pic d'Orhy (2 017 m) est le plus haut sommet du Pays Basque. Depuis Larrau, le sentier monte régulièrement à travers les estives de la Soule, avec des vues progressives sur les vallées basques et les premiers sommets pyrénéens. Au sommet : panorama de 360° sur 3 pays.",
    depart: "Larrau (64560) — parking du village",
    balisage: "Sentiers PR balisés jaune + GR 10 final",
    highlights: ["Plus haut sommet du Pays Basque", "Vue sur 3 pays", "Estives de Soule authentiques"],
    links: [
      { icon: "📷", label: "Altituderando – Orhy", url: "https://www.altituderando.com/Pic-d-Orhy-2017m-depuis-Larrau" },
      { icon: "📍", label: "AllTrails – Orhy", url: "https://www.alltrails.com/fr/randonnee/france/pyrenees-atlantiques/pic-d-orhy" },
      { icon: "🗺️", label: "Tourisme Soule", url: "https://www.tourisme-soule.com" },
    ],
  },
  {
    id: 15, slug: "trois-couronnes-espagne",
    emoji: "👑", title: "Les Trois Couronnes – Urrugune",
    region: "Labourd (côté espagnol accessible)", zone: "paysbasque",
    type: "journee", level: "facile", levelLabel: "Facile",
    distance: "11 km", duree: "4h", denivelé: "680 m",
    distanceBayonne: "35 min de Bayonne",
    img: "https://images.unsplash.com/photo-1500534314209-a25ddb2bd429?w=800&q=80",
    description: "Les Tres Coronas (813 m) depuis le hameau d'Urrugune. Ce sommet légendaire, reconnaissable à ses trois bourrelets rocheux, domine Hendaye et la Bidassoa. Vue imprenable sur la côte basque franco-espagnole, l'estuaire et les premières crêtes pyrénéennes.",
    depart: "Urrugune / Urrugne (64122) — parking Mairie",
    balisage: "Sentiers balisés jaune locaux",
    highlights: ["Vue sur la frontière franco-espagnole", "Sommet mythique région", "Accessible en famille"],
    links: [
      { icon: "📍", label: "AllTrails – Tres Coronas", url: "https://www.alltrails.com/fr/randonnee/france/pyrenees-atlantiques/les-trois-couronnes-tres-coronas" },
      { icon: "🗺️", label: "Visorando", url: "https://www.visorando.com/randonnee-tres-coronas.html" },
    ],
  },
  {
    id: 16, slug: "pic-midi-bigorre-journee",
    emoji: "📡", title: "Pic du Midi de Bigorre (2 877 m) — Télécabine",
    region: "Hautes-Pyrénées (65)", zone: "pyrenees",
    type: "journee", level: "facile", levelLabel: "Facile (câble)",
    distance: "4 km", duree: "2h–3h", denivelé: "300 m",
    distanceBayonne: "2h30 de Bayonne",
    img: "https://images.unsplash.com/photo-1519681393784-d120267933ba?w=800&q=80",
    description: "Avec la télécabine du Pic du Midi, vous atteignez 2 877 m sans transpirer. L'observatoire astronomique, l'un des plus importants au monde, et le panorama sur 400 km de Pyrénées en font une journée incontournable pour toute la famille. Possibilité de randonner sur les crêtes alentour.",
    depart: "La Mongie (65200) — base des télécabines",
    balisage: "Sentiers balisés depuis le sommet",
    highlights: ["Observatoire astronomique unique", "Vue 400 km de Pyrénées", "Accessible à tous"],
    links: [
      { icon: "🎿", label: "Pic du Midi Officiel", url: "https://www.picdumidi.com", note: "Réservation télécabine" },
      { icon: "📷", label: "Altituderando – Pic du Midi", url: "https://www.altituderando.com/Pic-du-Midi-de-Bigorre" },
    ],
  },
  {
    id: 17, slug: "ossau-bious-artigues",
    emoji: "🏔️", title: "Lac de Bious-Artigues – Tour du Lac",
    region: "Vallée d'Ossau (64)", zone: "pyrenees",
    type: "journee", level: "facile", levelLabel: "Facile",
    distance: "9 km", duree: "2h30", denivelé: "200 m",
    distanceBayonne: "1h45 de Bayonne",
    img: "https://images.unsplash.com/photo-1609766857823-56b5f81a7d67?w=800&q=80",
    description: "Le lac de Bious-Artigues, miroir du Pic du Midi d'Ossau, est l'une des images les plus reproduites des Pyrénées. Ce tour de lac facile en famille reste l'une des randonnées les plus populaires de la vallée d'Ossau. Parfait pour initier les enfants à la montagne.",
    depart: "Parking lac de Bious-Artigues — Gabas (64440)",
    balisage: "Balisage rouge/blanc GR 10 + PR local",
    highlights: ["Vue iconique Midi d'Ossau", "Tour de lac facile", "Idéal enfants dès 5 ans"],
    links: [
      { icon: "🗺️", label: "Wikiloc – Bious-Artigues", url: "https://fr.wikiloc.com/itineraires/lac-de-bious-artigues" },
      { icon: "🌿", label: "Ossau Tourisme", url: "https://www.ossau-pyrenees.com" },
    ],
  },
  {
    id: 18, slug: "cascade-pont-espagne",
    emoji: "💦", title: "Lac de Gaube & Pont d'Espagne",
    region: "Hautes-Pyrénées (65)", zone: "pyrenees",
    type: "journee", level: "facile", levelLabel: "Facile",
    distance: "11 km", duree: "3h30", denivelé: "400 m",
    distanceBayonne: "2h de Bayonne",
    img: "https://images.unsplash.com/photo-1448375240586-882707db888b?w=800&q=80",
    description: "La vallée de Cauterets et ses cascades spectaculaires. Depuis le Pont d'Espagne (1 496 m), télécabine optionnelle jusqu'au lac de Gaube (1 725 m), lac glaciaire turquoise avec vue directe sur le Vignemale (3 298 m). Une demi-journée magique.",
    depart: "Pont d'Espagne, Cauterets (65110) — parking payant",
    balisage: "Sentiers balisés Parc National — excellent",
    highlights: ["Vue directe sur le Vignemale", "Lac de Gaube turquoise", "Cascades du Pont d'Espagne"],
    links: [
      { icon: "🎿", label: "Cauterets Tourisme", url: "https://www.cauterets.com" },
      { icon: "📍", label: "AllTrails – Lac de Gaube", url: "https://www.alltrails.com/fr/randonnee/france/hautes-pyrenees/lac-de-gaube" },
    ],
  },
  {
    id: 19, slug: "chemin-cretes-pays-basque",
    emoji: "🌅", title: "Chemin des Crêtes – Aldudes",
    region: "Basse-Navarre · Pays Basque", zone: "paysbasque",
    type: "journee", level: "modere", levelLabel: "Modéré",
    distance: "16 km", duree: "5h", denivelé: "750 m",
    distanceBayonne: "1h de Bayonne",
    img: "https://images.unsplash.com/photo-1469474968028-56623f02e42e?w=800&q=80",
    description: "La vallée des Aldudes, paradis du porc basque Kintoa (protégé AOP), abrite un chemin de crête solitaire entre France et Navarre. Un terrain herbeux impeccable, des vues infinies et la certitude de ne croiser presque personne. L'un des secrets les mieux gardés du Pays Basque.",
    depart: "Urepel (64430) — parking bord du gave",
    balisage: "Sentiers locaux balisés jaune-rouge",
    highlights: ["Vallée des Aldudes confidentielle", "Porc Kintoa (AOP basque)", "Vue France-Navarre"],
    links: [
      { icon: "🗺️", label: "Rando Pays Basque", url: "https://rando-pays-basque.info/basse-navarre/" },
      { icon: "🐷", label: "Pierre Oteiza (Kintoa)", url: "https://www.pierreoteiza.com" },
    ],
  },
  {
    id: 20, slug: "col-pourtalet-pic-midi-ossau",
    emoji: "🦅", title: "Pic du Midi d'Ossau (2 884 m) — Voie Normale",
    region: "Vallée d'Ossau (64)", zone: "pyrenees",
    type: "journee", level: "difficile", levelLabel: "Difficile",
    distance: "18 km", duree: "7h–9h", denivelé: "1 600 m",
    distanceBayonne: "1h45 de Bayonne",
    img: "https://images.unsplash.com/photo-1486870591958-9b9d0d1dda99?w=800&q=80",
    description: "La voie normale du Midi d'Ossau par la brèche du Capéran n'est pas une simple rando : c'est une course d'arête exposée (II/III en escalade), réservée aux randonneurs confirmés à l'aise en terrain rocheux. Le sommet (2 884 m) vaut chaque mètre de corde.",
    depart: "Parking lac de Bious-Artigues — Gabas (64440)",
    balisage: "GR 10 jusqu'au col · Cairns ensuite · Arête non balisée",
    highlights: ["Sommet iconique des Pyrénées", "Voie d'arête exposée", "Vautours fauves garantis"],
    links: [
      { icon: "📷", label: "Altituderando – Voie Normale", url: "https://www.altituderando.com/Le-Pic-du-Midi-d-Ossau-2884m-voie-normale" },
      { icon: "🗺️", label: "Wikiloc – Ossau sommet", url: "https://fr.wikiloc.com/itineraires/pic-du-midi-d-ossau-voie-normale" },
    ],
  },
  {
    id: 21, slug: "gorges-kakuetta-journee",
    emoji: "🌊", title: "Gorges de Kakuetta (journée)",
    region: "Soule · Pays Basque", zone: "paysbasque",
    type: "journee", level: "facile", levelLabel: "Facile",
    distance: "3 km", duree: "2h", denivelé: "100 m",
    distanceBayonne: "1h45 de Bayonne",
    img: "https://images.unsplash.com/photo-1418065460487-3e41a6c84dc5?w=800&q=80",
    description: "Les gorges de Kakuetta sont l'une des merveilles naturelles de la région. Formées par le gave de Sainte-Engrâce dans un calcaire blanc, elles s'élèvent jusqu'à 300 m de hauteur pour à peine 5 m de largeur. Fraîcheur garantie même en juillet. Gros sourcils à la cascade du fond.",
    depart: "Gorges de Kakuetta — Sainte-Engrâce (64560), parking payant",
    balisage: "Sentier aménagé et balisé dans les gorges",
    highlights: ["Canyon spectaculaire 300 m de haut", "Fraîcheur même en été", "Grande cascade au fond"],
    links: [
      { icon: "🌊", label: "Site officiel Kakuetta", url: "https://www.gorges-kakuetta.com" },
      { icon: "📍", label: "AllTrails – Kakuetta", url: "https://www.alltrails.com/fr/randonnee/france/pyrenees-atlantiques/gorges-de-kakuetta" },
    ],
  },
  {
    id: 22, slug: "table-des-trois-rois",
    emoji: "👑", title: "Table des Trois Rois (2 421 m)",
    region: "Pyrénées-Atlantiques (64)", zone: "pyrenees",
    type: "journee", level: "modere", levelLabel: "Modéré",
    distance: "17 km", duree: "6h", denivelé: "1 100 m",
    distanceBayonne: "2h de Bayonne",
    img: "https://images.unsplash.com/photo-1509316785289-025f5b846b35?w=800&q=80",
    description: "La Table des Trois Rois est le point où se rencontraient les royaumes de France, de Navarre et d'Aragon. Depuis Lescun, l'un des plus beaux villages de France, la montée passe par les célèbres Aiguilles d'Ansabère avant d'atteindre ce balcon frontière exceptionnel.",
    depart: "Lescun (64490) — parking village",
    balisage: "GR 10 + sentiers PR jaune",
    highlights: ["Point triple France-Navarre-Aragon", "Aiguilles d'Ansabère", "Lescun (+beau village de France)"],
    links: [
      { icon: "📷", label: "Altituderando – Table des 3 Rois", url: "https://www.altituderando.com/Table-des-Trois-Rois-2421m" },
      { icon: "📍", label: "AllTrails", url: "https://www.alltrails.com/fr/randonnee/france/pyrenees-atlantiques/table-des-trois-rois" },
    ],
  },
  {
    id: 23, slug: "brèche-roland-journee",
    emoji: "⚔️", title: "La Brèche de Roland (2 807 m)",
    region: "Hautes-Pyrénées (65)", zone: "pyrenees",
    type: "journee", level: "difficile", levelLabel: "Difficile",
    distance: "20 km", duree: "7h–8h", denivelé: "1 600 m",
    distanceBayonne: "2h30 de Bayonne",
    img: "https://images.unsplash.com/photo-1464822759023-fed622ff2c3b?w=800&q=80",
    description: "La Brèche de Roland est une encoche naturelle de 100 m de large et 40 m de haut dans la muraille des Pyrénées, selon la légende taillée par le paladin Roland. Depuis la Sarradets, la progression est engagée — passages neigeux probables jusqu'en août. Vue sur le Cirque de Gavarnie d'un côté, l'Espagne de l'autre.",
    depart: "Gavarnie (65120) — parking village",
    balisage: "GR 10 + sentiers balisés HRP",
    highlights: ["Brèche légendaire de Roland", "Vue sur 2 pays", "Passage neigeux estival"],
    links: [
      { icon: "📷", label: "Altituderando – Brèche", url: "https://www.altituderando.com/La-breche-de-Roland-depuis-Gavarnie" },
      { icon: "🏞️", label: "Parc National", url: "https://www.pyrenees-parcnational.fr" },
    ],
  },
  {
    id: 24, slug: "font-romeu-carlit-journee",
    emoji: "🌞", title: "Pic Carlit (2 921 m) depuis les Bouillouses",
    region: "Cerdagne (66)", zone: "orientales",
    type: "journee", level: "modere", levelLabel: "Modéré",
    distance: "16 km", duree: "5h–6h", denivelé: "950 m",
    distanceBayonne: "4h de Bayonne",
    img: "https://images.unsplash.com/photo-1519681393784-d120267933ba?w=800&q=80",
    description: "Le Pic Carlit (2 921 m) est le toit des Pyrénées orientales. Depuis le lac des Bouillouses, le sentier traverse un labyrinthe de lacs glaciaires avant d'atteindre un sommet panoramique exceptionnel. Soleil garanti à 300 jours par an en Cerdagne.",
    depart: "Lac des Bouillouses (66210) — parking payant",
    balisage: "Sentiers balisés RNR Carlit jaune",
    highlights: ["Toit des Pyrénées orientales", "Labyrinthe de lacs glaciaires", "Cerdagne — 300 jours de soleil"],
    links: [
      { icon: "📷", label: "Altituderando – Carlit", url: "https://www.altituderando.com/Pic-Carlit-2921m-depuis-Bouillouses" },
      { icon: "🌿", label: "RNN Carlit", url: "https://www.reserves-naturelles.org/carlit" },
      { icon: "📍", label: "AllTrails – Carlit", url: "https://www.alltrails.com/fr/randonnee/france/pyrenees-orientales/pic-carlit" },
    ],
  },
];

// ── MATÉRIEL ─────────────────────────────────────────────────
const MATERIEL = [
  { icon: "🏕️", name: "Tente 3 saisons légère (2–3 pers.)", prio: "rouge", pLabel: "Indispensable", prix: "80–250 €", ou: "Décathlon, MSR, Salomon" },
  { icon: "🛌", name: "Sac de couchage (confort 0°C à −5°C)", prio: "rouge", pLabel: "Indispensable", prix: "60–200 €", ou: "Décathlon Forclaz, Vaude, Rab" },
  { icon: "🛏️", name: "Matelas isolant (Thermarest ou mousse)", prio: "rouge", pLabel: "Indispensable", prix: "20–80 €", ou: "Décathlon, Sea to Summit" },
  { icon: "💧", name: "Filtre à eau (Sawyer Squeeze ou Katadyn)", prio: "orange", pLabel: "Très utile", prix: "30–60 €", ou: "Décathlon, Amazon" },
  { icon: "🍳", name: "Réchaud + gaz + casserole légère", prio: "orange", pLabel: "Très utile", prix: "30–80 €", ou: "MSR, Jetboil, Décathlon" },
  { icon: "🥘", name: "Nourriture lyophilisée / déshydratée", prio: "orange", pLabel: "Très utile", prix: "5–12 €/repas", ou: "Freeze-dry.fr, Trek'n'Eat" },
  { icon: "🧃", name: "Gourde 1L + poche à eau 2L", prio: "orange", pLabel: "Très utile", prix: "10–30 €", ou: "Nalgene, Hydrapak" },
  { icon: "🔦", name: "Lampe frontale + piles de rechange", prio: "jaune", pLabel: "Utile", prix: "15–40 €", ou: "Petzl, Black Diamond" },
  { icon: "🩹", name: "Trousse de premiers secours", prio: "jaune", pLabel: "Utile", prix: "15–30 €", ou: "Pharmacie, Décathlon" },
  { icon: "📱", name: "App GPS offline (Maps.me / OruxMaps / Komoot)", prio: "jaune", pLabel: "Utile", prix: "Gratuit–10€", ou: "Téléchargez avant de partir !" },
  { icon: "🧴", name: "Crème solaire SPF 50+ + anti-insectes", prio: "jaune", pLabel: "Utile", prix: "10–20 €", ou: "Pharmacie, supermarché" },
  { icon: "🧦", name: "Vêtements de rechange + couche chaude", prio: "orange", pLabel: "Très utile", prix: "Variable", ou: "Polaire ou doudoune légère" },
  { icon: "🧊", name: "Crampons légers (circuits ≥ Modéré+, juillet)", prio: "orange", pLabel: "Très utile (selon niveau)", prix: "30–80 €", ou: "Décathlon, Black Diamond" },
  { icon: "🪝", name: "Bâtons de randonnée télescopiques", prio: "orange", pLabel: "Très utile", prix: "30–120 €", ou: "Leki, Black Diamond, Décathlon" },
];

const URGENCES = [
  { label: "Urgence universelle", num: "112", note: "Fonctionne même sans réseau sur certains opérateurs" },
  { label: "PGHM Pau", num: "05 62 92 41 41", note: "Secours montagne Pyrénées-Atlantiques (64)" },
  { label: "PGHM Tarbes", num: "05 62 44 04 44", note: "Secours montagne Hautes-Pyrénées (65)" },
  { label: "CRS Alpes (Ariège / Py. Orientales)", num: "04 79 34 34 02", note: "Secours montagne 09 et 66" },
];

// ── RÈGLES BIVOUAC ───────────────────────────────────────────
const REGLES_BIVOUAC = [
  { icon: "🌙", title: "Horaires stricts", desc: "Autorisé de 19h à 9h uniquement — jamais en plein jour." },
  { icon: "📏", title: "Distance minimale", desc: "À plus d'1h de marche des routes, parkings et zones habitées." },
  { icon: "🏞️", title: "Cœurs de parcs", desc: "Interdit dans les cœurs du Parc National des Pyrénées et des réserves naturelles nationales." },
  { icon: "🔥", title: "Feu interdit", desc: "Aucun feu de camp — réchaud à gaz uniquement. Réglementation très stricte." },
  { icon: "🗑️", title: "Zéro déchet", desc: "Tout emporter — déchets, papier toilette, mégots. Laisser l'endroit vierge." },
  { icon: "💩", title: "Déjections humaines", desc: "Creuser un trou de 20 cm minimum, à 50 m de tout cours d'eau. Emporter les papiers." },
  { icon: "🌊", title: "Eaux propres", desc: "Ne jamais laver vaisselle ou corps directement dans un lac ou cours d'eau — utiliser un seau à 50 m minimum." },
  { icon: "🐑", title: "Faune et troupeaux", desc: "Garder distances avec les troupeaux et la faune sauvage. Chiens tenus en laisse." },
];