// ═══════════════════════════════════════════════════════════
// BIVOUAC PYRÉNÉES — Shared Data
// ═══════════════════════════════════════════════════════════

const CIRCUITS = [
  {
    id: 1, slug: "lacs-ayous",
    emoji: "🏔️", title: "Tour des Lacs d'Ayous",
    region: "Vallée d'Ossau (64)", zone: "pyrenees",
    level: "facile", levelLabel: "Facile+", levelColor: "#52b788",
    jours: 2, kmJour: 10, totalKm: 20, denivelé: 1100,
    saison: "Juin – octobre",
    img: "https://images.unsplash.com/photo-1609766857823-56b5f81a7d67?w=1200&q=85",
    imgThumb: "https://images.unsplash.com/photo-1609766857823-56b5f81a7d67?w=600&q=75",
    depart: "Parking lac de Bious-Artigues — Gabas (64440)",
    acces: "Depuis Pau : 1h15 · Depuis Bayonne : 1h45",
    sommet: "Col d'Ayous (2 185 m)",
    balisage: "GR 10 rouge/blanc — balisage irréprochable",
    eau: "Nombreuses sources et lacs — eau potable après filtration",
    ravito: "Aucun en chemin · Village de Laruns (25 km)",
    carte: "IGN Top 25 · 1547 OT",
    description: "Le lac d'Ayous est l'un des joyaux des Pyrénées béarnaises. Face au Pic du Midi d'Ossau qui se reflète dans ses eaux émeraude, ce circuit en boucle facile offre un bivouac d'exception pour une première nuit en altitude.",
    etapes: [
      { jour: "J1", troncon: "Bious-Artigues → Lac d'Ayous → Col d'Ayous → Lac Bersau", km: "10 km", deni: "+1 100/−300 m", bivouac: "Rive du lac Bersau (2 083 m) — plat, abrité, vue sur le Midi d'Ossau" },
      { jour: "J2", troncon: "Lac Bersau → Lac Roumassot → Lac de Casterau → Bious-Artigues", km: "10 km", deni: "+100/−900 m", bivouac: "Retour au point de départ" },
    ],
    tips: [
      "Le lac d'Ayous offre l'un des plus beaux couchers de soleil des Pyrénées, face au Pic du Midi d'Ossau.",
      "Le J2 est en descente : parfait quand on est un peu fatigués le deuxième jour !",
      "Balisage GR 10 irréprochable — impossible de se perdre, même sans GPS.",
      "Zone fréquentée : rassurante pour un premier bivouac.",
    ],
    links: [
      { icon: "⛺", label: "Refuge d'Ayous", url: "https://www.refuge-ayous.com", note: "Plan B si mauvais temps" },
      { icon: "🗺️", label: "Wikiloc – Lacs d'Ayous", url: "https://fr.wikiloc.com/itineraires-randonnee-pedestres/tour-des-lacs-d-ayous", note: "Trace GPS" },
      { icon: "📷", label: "Altituderando", url: "https://www.altituderando.com/Tour-des-lacs-d-Ayous", note: "Photos + description" },
      { icon: "🌤️", label: "Météo montagne", url: "https://meteofrance.com/meteo-montagne/pyrenees", note: "À consulter la veille" },
    ],
    highlights: ["Vue iconique sur le Midi d'Ossau", "Lacs d'altitude émeraude", "Idéal premier bivouac"],
  },
  {
    id: 2, slug: "crete-iparla",
    emoji: "🌿", title: "Crête d'Iparla – Boucle basque",
    region: "Pays Basque intérieur (64)", zone: "paysbasque",
    level: "facile", levelLabel: "Facile+", levelColor: "#52b788",
    jours: 2, kmJour: 11, totalKm: 22, denivelé: 1000,
    saison: "Avril – novembre",
    img: "https://images.unsplash.com/photo-1499856871958-5b9357976b82?w=1200&q=85",
    imgThumb: "https://images.unsplash.com/photo-1499856871958-5b9357976b82?w=600&q=75",
    depart: "Village de Bidarray (64780) — parking de l'église, gratuit",
    acces: "Depuis Bayonne : 40 min · Depuis Pau : 1h30",
    sommet: "Crête d'Iparla (1 044 m)",
    balisage: "Sentiers balisés jaune-rouge + GR 10",
    eau: "Sources rares en été — emportez 2L/pers min.",
    ravito: "Bidarray : boulangerie, épicerie, restaurants",
    carte: "IGN Top 25 · 1346 OT",
    description: "La crête d'Iparla est l'une des plus belles lignes de crête du Pays Basque. Pelouses rases, pottoks en liberté et vue à 360° sur l'Atlantique d'un côté, les Pyrénées de l'autre. Un bivouac dans les étoiles sur les hauts plateaux basques.",
    etapes: [
      { jour: "J1", troncon: "Bidarray → Montée crête d'Iparla → Sommet Artzamendi Nord", km: "11 km", deni: "+1 000/−200 m", bivouac: "Crête d'Iparla (900–1 000 m) — pelouses rases, vue 360°" },
      { jour: "J2", troncon: "Crête → Col de Harrieta → Forêt de Hayra → Bidarray", km: "11 km", deni: "+200/−1 000 m", bivouac: "Retour au point de départ" },
    ],
    tips: [
      "Pelouses basques, moutons, pottoks et vue sur l'Atlantique — ambiance totalement différente des Pyrénées.",
      "Bivouac sur les pelouses de crête : herbe rase, terrain plat naturel.",
      "Le village de Bidarray est charmant — parfait pour un dîner le soir du retour.",
    ],
    links: [
      { icon: "🗺️", label: "Visorando – Crête d'Iparla", url: "https://www.visorando.com/randonnee-crete-d-iparla", note: "Description + photos" },
      { icon: "📍", label: "AllTrails – Iparla Ridge", url: "https://www.alltrails.com/trail/france/pyrenees-atlantiques/iparla-ridge", note: "Carte interactive" },
      { icon: "🌤️", label: "Météo Bidarray", url: "https://meteofrance.com/previsions-meteo-france/bidarray/64780", note: "Prévisions locales" },
    ],
    highlights: ["Vue sur l'Atlantique", "Pottoks en liberté", "Village basque authentique"],
  },
  {
    id: 3, slug: "foret-iraty",
    emoji: "🌲", title: "Tour de la Forêt d'Iraty",
    region: "Pays Basque / Pyrénées (64)", zone: "paysbasque",
    level: "facile", levelLabel: "Facile", levelColor: "#52b788",
    jours: 3, kmJour: 10, totalKm: 30, denivelé: 1200,
    saison: "Mai – octobre",
    img: "https://images.unsplash.com/photo-1448375240586-882707db888b?w=1200&q=85",
    imgThumb: "https://images.unsplash.com/photo-1448375240586-882707db888b?w=600&q=75",
    depart: "Chalet Pedro, Plateau d'Iraty (64560)",
    acces: "Depuis Bayonne : 1h30 · Depuis Pau : 1h45",
    sommet: "Col Bagargui (1 327 m)",
    balisage: "GR 10 + sentiers forestiers jaune",
    eau: "Rivières et fontaines — eau très abondante",
    ravito: "Chalet Pedro (restaurant, épicerie sommaire)",
    carte: "IGN Top 25 · 1346 OT",
    description: "Iraty, c'est la plus grande hêtraie-sapinière d'Europe occidentale. Trois jours dans cette cathédrale végétale, entre forêts profondes, estives ouvertes et vestiges romains. Un bivouac hors du commun, enveloppé par les arbres.",
    etapes: [
      { jour: "J1", troncon: "Chalet Pedro → Forêt d'Iraty → Lac Arphia → Col Bagargui", km: "10 km", deni: "+600/−200 m", bivouac: "Bords du lac Arphia (1 265 m) — lac en forêt" },
      { jour: "J2", troncon: "Col Bagargui → Crête des Urculu → Tour d'Urculu → Estive", km: "10 km", deni: "+500/−400 m", bivouac: "Estives d'Orgambidexka (1 300 m)" },
      { jour: "J3", troncon: "Orgambidexka → Forêt de Soule → Chalet Pedro", km: "10 km", deni: "+100/−700 m", bivouac: "Retour au point de départ" },
    ],
    tips: [
      "La forêt d'Iraty est la plus grande hêtraie-sapinière d'Europe — ambiance forestière magique.",
      "La Tour d'Urculu (J2) est un ancien fortin romain — belle surprise culturelle.",
      "Accessible sans jamais dépasser 1 350 m — aucun risque lié à l'altitude.",
    ],
    links: [
      { icon: "🌲", label: "Site officiel Iraty", url: "https://www.paysbasque-foret-iraty.com", note: "Cartes + infos" },
      { icon: "🏠", label: "Chalet Pedro", url: "https://www.chaletpedro.com", note: "Plan B" },
      { icon: "📷", label: "Altituderando – Iraty", url: "https://www.altituderando.com/La-foret-d-Iraty", note: "Photos de saison" },
    ],
    highlights: ["Plus grande forêt d'Europe occidentale", "Fortin romain Urculu", "Dénivelés très doux"],
  },
  {
    id: 4, slug: "artouste-soussouéou",
    emoji: "🦅", title: "Boucle Lac d'Artouste & Soussouéou",
    region: "Vallée d'Ossau (64)", zone: "pyrenees",
    level: "modere", levelLabel: "Modéré", levelColor: "#e9c46a",
    jours: 3, kmJour: 10, totalKm: 30, denivelé: 1500,
    saison: "Juillet – septembre",
    img: "https://images.unsplash.com/photo-1506905925346-21bda4d32df4?w=1200&q=85",
    imgThumb: "https://images.unsplash.com/photo-1506905925346-21bda4d32df4?w=600&q=75",
    depart: "Fabrèges (64440) — parking téléphérique d'Artouste",
    acces: "Depuis Pau : 1h20 · Depuis Bayonne : 1h50",
    sommet: "Hourquette d'Arre (2 465 m)",
    balisage: "GR 10 + sentiers balisés Ossau",
    eau: "Nombreux lacs et ruisseaux — eau abondante",
    ravito: "Aucun en chemin (3 jours de nourriture)",
    carte: "IGN Top 25 · 1547 OT",
    description: "Montez au lac d'Artouste en petit train centenaire, puis descendez à travers des paysages de lacs sauvages et de cascades. Ce circuit combine le plus haut train touristique de France avec deux nuits de bivouac dans des paysages exceptionnels.",
    etapes: [
      { jour: "J1", troncon: "Fabrèges → Train d'Artouste → Lac d'Artouste → Lac d'Arrious", km: "10 km", deni: "+400/−200 m", bivouac: "Lac d'Arrious (2 072 m)" },
      { jour: "J2", troncon: "Lac d'Arrious → Hourquette d'Arre → Lacs de Soussouéou", km: "10 km", deni: "+600/−1 100 m", bivouac: "Bords du gave de Soussouéou (1 350 m)" },
      { jour: "J3", troncon: "Soussouéou → Sentier des cascades → Fabrèges", km: "10 km", deni: "+400/−650 m", bivouac: "Retour au point de départ" },
    ],
    tips: [
      "Le train d'Artouste est unique : le plus haut train touristique de France (1 950 m). Réservez à l'avance !",
      "Les lacs de Soussouéou sont peu fréquentés — spots de bivouac de rêve.",
      "Le retour par les cascades de Soussouéou est spectaculaire.",
    ],
    links: [
      { icon: "🚂", label: "Train d'Artouste", url: "https://www.artouste.com", note: "Réservation obligatoire" },
      { icon: "🗺️", label: "Wikiloc – Soussouéou", url: "https://fr.wikiloc.com/itineraires/lacs-de-soussoueoeu-ossau", note: "Traces GPS" },
      { icon: "📷", label: "Altituderando – Arrious", url: "https://www.altituderando.com/Lac-d-Arrious", note: "Fiche détaillée" },
    ],
    highlights: ["Train touristique à 1 950 m", "Cascades de Soussouéou", "Lacs sauvages peu fréquentés"],
  },
  {
    id: 5, slug: "pays-basque-interieur",
    emoji: "🌿", title: "Tour du Pays Basque intérieur",
    region: "Pays Basque · France", zone: "paysbasque",
    level: "modere", levelLabel: "Modéré", levelColor: "#e9c46a",
    jours: 3, kmJour: 18, totalKm: 55, denivelé: 2400,
    saison: "Mai – octobre",
    img: "https://images.unsplash.com/photo-1469474968028-56623f02e42e?w=1200&q=85",
    imgThumb: "https://images.unsplash.com/photo-1469474968028-56623f02e42e?w=600&q=75",
    depart: "Saint-Jean-Pied-de-Port (64220) — parking porte Saint-Jacques",
    acces: "Depuis Bayonne : 55 min · Depuis Pau : 1h20",
    sommet: "Sommet d'Occabé (1 456 m)",
    balisage: "GR 10 + sentiers locaux jaune",
    eau: "Sources en altitude, villages de Banca et Aldudes",
    ravito: "Villages traversés : Banca, Aldudes",
    carte: "IGN Top 25 · 1346 OT",
    description: "Au départ de Saint-Jean-Pied-de-Port, porte des pèlerins de Compostelle, ce tour traverse le cœur du Pays Basque intérieur. Crêtes, estives, villages typiques et panoramas sur l'Atlantique composent un itinéraire à la fois physique et culturel.",
    etapes: [
      { jour: "J1", troncon: "Saint-Jean-Pied-de-Port → Col d'Ursuia → Crête d'Iparla", km: "18 km", deni: "+1 050/−250 m", bivouac: "Crête d'Iparla (1 044 m)" },
      { jour: "J2", troncon: "Crête d'Iparla → Forêt d'Hayra → Sommet d'Occabé", km: "20 km", deni: "+950/−700 m", bivouac: "Plateau sous Occabé (1 350 m)" },
      { jour: "J3", troncon: "Occabé → Col de Burdincurutcheta → Saint-Jean-Pied-de-Port", km: "17 km", deni: "+400/−1 450 m", bivouac: "Retour au point de départ" },
    ],
    tips: [
      "Remplissez vos gourdes au départ : les sources sont parfois taries en été.",
      "La crête d'Iparla est exposée au vent — prévoyez un abri léger.",
      "Ce circuit peut se raccourcir en 2 jours pour les plus rapides.",
    ],
    links: [
      { icon: "🗺️", label: "IGNrando", url: "https://ignrando.fr/fr/communautes-et-parcours/detail-un-parcours?id=53791", note: "Trace GPS officielle" },
      { icon: "📷", label: "Visorando", url: "https://www.visorando.com/randonnee-tour-du-pays-basque/", note: "Description + photos" },
      { icon: "🌤️", label: "Météo Pyrénées", url: "https://meteofrance.com/meteo-montagne/pyrenees", note: "Prévisions" },
    ],
    highlights: ["Départ depuis Saint-Jean-Pied-de-Port", "Villages basques authentiques", "Crêtes et estives"],
  },
  {
    id: 6, slug: "hrp-ossoue-vignemale",
    emoji: "⛰️", title: "Boucle HRP Ossoue – Vignemale",
    region: "Pyrénées centrales (65)", zone: "pyrenees",
    level: "difficile", levelLabel: "Difficile", levelColor: "#c96a1e",
    jours: 4, kmJour: 17, totalKm: 68, denivelé: 4200,
    saison: "Juillet – septembre",
    img: "https://images.unsplash.com/photo-1464822759023-fed622ff2c3b?w=1200&q=85",
    imgThumb: "https://images.unsplash.com/photo-1464822759023-fed622ff2c3b?w=600&q=75",
    depart: "Pont d'Espagne, Cauterets (65110) — parking payant",
    acces: "Depuis Tarbes : 1h · Depuis Pau : 1h30",
    sommet: "Hourquette d'Ossoue (2 734 m)",
    balisage: "HRP jaune/rouge + GR 10",
    eau: "Nombreux lacs · Refuge Baysellance (gardé)",
    ravito: "Refuges des Oulettes + Baysellance",
    carte: "IGN Top 25 · 1748 OT",
    description: "L'itinéraire de la Haute Randonnée Pyrénéenne dans sa version la plus sauvage. Le Vignemale (3 298 m) en toile de fond, des lacs glaciaires à perte de vue, et le Refuge de Baysellance, le plus haut refuge gardé de France.",
    etapes: [
      { jour: "J1", troncon: "Pont d'Espagne → Lac de Gaube → Refuge des Oulettes", km: "14 km", deni: "+1 200/−100 m", bivouac: "Refuge des Oulettes (2 151 m)" },
      { jour: "J2", troncon: "Oulettes → Hourquette d'Ossoue → Refuge de Baysellance", km: "12 km", deni: "+1 050/−600 m", bivouac: "Refuge Baysellance (2 651 m)" },
      { jour: "J3", troncon: "Baysellance → Barrage d'Ossoue → Gavarnie", km: "24 km", deni: "+600/−1 900 m", bivouac: "Zone bivouac Gavarnie (1 600 m)" },
      { jour: "J4", troncon: "Gavarnie → Col des Tentes → Pont d'Espagne", km: "18 km", deni: "+1 350/−1 600 m", bivouac: "Retour au point de départ" },
    ],
    tips: [
      "Réservez les refuges au minimum 4 semaines à l'avance en juillet-août.",
      "La Hourquette d'Ossoue peut être enneigée jusqu'en juillet — crampons légers utiles.",
      "Nuits en altitude : prévoyez des vêtements chauds, même en été.",
    ],
    links: [
      { icon: "⛺", label: "Refuge des Oulettes", url: "https://refugedesoulettes.ffcam.fr", note: "Réservation obligatoire" },
      { icon: "⛺", label: "Refuge de Baysellance", url: "https://www.refuges-pyrenees.com/refuge-baysellance", note: "Plus haut refuge de France" },
      { icon: "🏞️", label: "Parc National Pyrénées", url: "https://www.pyrenees-parcnational.fr", note: "Règles bivouac" },
    ],
    highlights: ["Vignemale en toile de fond", "Refuge Baysellance (2 651 m)", "Cirque de Gavarnie"],
  },
  {
    id: 7, slug: "lacs-ossau",
    emoji: "🦅", title: "Tour des Lacs d'Ossau",
    region: "Vallée d'Ossau · Béarn (64)", zone: "pyrenees",
    level: "modere", levelLabel: "Modéré", levelColor: "#e9c46a",
    jours: 3, kmJour: 17, totalKm: 52, denivelé: 3100,
    saison: "Juin – octobre",
    img: "https://images.unsplash.com/photo-1501854140801-50d01698950b?w=1200&q=85",
    imgThumb: "https://images.unsplash.com/photo-1501854140801-50d01698950b?w=600&q=75",
    depart: "Gabas (64440) — parking lac de Bious-Artigues",
    acces: "Depuis Pau : 1h15 · Depuis Bayonne : 1h45",
    sommet: "Col de Peyreget (2 208 m)",
    balisage: "GR 10 + sentiers balisés Ossau",
    eau: "Lacs de Bious, d'Anglas, de Peyreget",
    ravito: "Cabane de Peyreget (non gardée)",
    carte: "IGN Top 25 · 1547 OT",
    description: "Un enchaînement de lacs d'altitude comme nulle part ailleurs dans les Pyrénées. Chaque soir, le bivouac se fait au bord d'un lac différent, sous le regard permanent du Pic du Midi d'Ossau — le « Jean-Pierre » des locaux.",
    etapes: [
      { jour: "J1", troncon: "Bious-Artigues → Lacs d'Ayous → Col d'Ayous", km: "17 km", deni: "+1 150/−350 m", bivouac: "Lac d'Ayous (2 185 m)" },
      { jour: "J2", troncon: "Col d'Ayous → Lac de Bersau → Lac d'Anglas → Col d'Anglas", km: "19 km", deni: "+1 100/−950 m", bivouac: "Lac d'Anglas (2 065 m)" },
      { jour: "J3", troncon: "Col d'Anglas → Lac de Peyreget → Col de Peyreget → Bious-Artigues", km: "16 km", deni: "+850/−1 750 m", bivouac: "Retour au point de départ" },
    ],
    tips: [
      "Évitez ce circuit par temps d'orage : les crêtes sont très exposées à la foudre.",
      "Les isards et vautours fauves sont fréquents — emportez des jumelles.",
      "Nuit différente à chaque étape : 3 lacs, 3 atmosphères.",
    ],
    links: [
      { icon: "⛺", label: "Refuge d'Ayous", url: "https://www.refuge-ayous.com", note: "Gardé, dortoirs" },
      { icon: "🗺️", label: "Wikiloc – Ossau", url: "https://fr.wikiloc.com/itineraires-randonnee-pedestres/tour-des-lacs-ossau", note: "GPS track" },
      { icon: "🌿", label: "Vallée d'Ossau Tourisme", url: "https://www.ossau-pyrenees.com/randonnees", note: "Infos locales" },
    ],
    highlights: ["3 lacs en 3 nuits", "Isards et vautours fauves", "Pic du Midi d'Ossau omniprésent"],
  },
  {
    id: 8, slug: "cerdagne-carlit",
    emoji: "🌞", title: "Boucle Cerdagne – Pic Carlit",
    region: "Pyrénées orientales (66)", zone: "pyrenees",
    level: "difficile", levelLabel: "Difficile", levelColor: "#c96a1e",
    jours: 5, kmJour: 18, totalKm: 90, denivelé: 5500,
    saison: "Juillet – mi-septembre",
    img: "https://images.unsplash.com/photo-1519681393784-d120267933ba?w=1200&q=85",
    imgThumb: "https://images.unsplash.com/photo-1519681393784-d120267933ba?w=600&q=75",
    depart: "Les Angles (66210) — parking lac des Bouillouses",
    acces: "Depuis Perpignan : 1h45 · Depuis Toulouse : 2h30",
    sommet: "Pic Carlit (2 921 m) — point culminant des Pyrénées orientales",
    balisage: "GR 10 + sentiers RNR Carlit",
    eau: "Nombreux lacs, Lac des Bouillouses",
    ravito: "Gîte des Bouillouses au départ",
    carte: "IGN Top 25 · 2249 ET",
    description: "La Cerdagne, pays du soleil. 5 jours dans le plus grand espace lacustre des Pyrénées, couronnés par l'ascension du Pic Carlit (2 921 m). Lacs, tourbières, crêtes frontière et lumière dorée de la montagne catalane.",
    etapes: [
      { jour: "J1", troncon: "Bouillouses → Tour du lac → Lac du Campcardos", km: "16 km", deni: "+900/−500 m", bivouac: "Lac du Campcardos (2 310 m)" },
      { jour: "J2", troncon: "Campcardos → Portella de Mantet → Mantet", km: "20 km", deni: "+1 200/−1 050 m", bivouac: "Zone bivouac Mantet (1 700 m)" },
      { jour: "J3", troncon: "Mantet → Col de la Comassa → Lac de Lanós", km: "18 km", deni: "+1 050/−900 m", bivouac: "Lac de Lanós (2 213 m)" },
      { jour: "J4", troncon: "Lac de Lanós → Ascension Pic Carlit → Bouillouses", km: "20 km", deni: "+1 550/−1 500 m", bivouac: "Lac des Bouillouses (2 017 m)" },
      { jour: "J5", troncon: "Tour final Bouillouses → Les Angles", km: "16 km", deni: "+800/−900 m", bivouac: "Retour au point de départ" },
    ],
    tips: [
      "La Cerdagne est l'une des régions les plus ensoleillées de France — protection solaire obligatoire.",
      "Les Bouillouses sont accessibles en navette depuis Les Angles en juillet-août.",
      "Orages fréquents l'après-midi : partez tôt pour les crêtes.",
    ],
    links: [
      { icon: "🌿", label: "RNN Carlit", url: "https://www.reserves-naturelles.org/carlit", note: "Réglementation + faune" },
      { icon: "🏠", label: "Gîte des Bouillouses", url: "https://www.bouillouses.fr", note: "Hébergement départ" },
      { icon: "🗺️", label: "Pyrénées Catalanes", url: "https://www.pyrenees-catalanes.fr", note: "Infos régionales" },
    ],
    highlights: ["Pic Carlit (2 921 m)", "Cerdagne — pays du soleil", "Espace lacustre unique"],
  },
  {
    id: 9, slug: "midi-ossau-espagne",
    emoji: "🏔️", title: "Grand Tour du Midi d'Ossau",
    region: "Béarn / Aragon (64 · ES)", zone: "pyrenees",
    level: "difficile", levelLabel: "Difficile", levelColor: "#c96a1e",
    jours: 4, kmJour: 15, totalKm: 62, denivelé: 3800,
    saison: "Juillet – septembre",
    img: "https://images.unsplash.com/photo-1486870591958-9b9d0d1dda99?w=1200&q=85",
    imgThumb: "https://images.unsplash.com/photo-1486870591958-9b9d0d1dda99?w=600&q=75",
    depart: "Gabas (64440) — parking lac de Bious-Artigues",
    acces: "Depuis Pau : 1h15 · Depuis Bayonne : 1h45",
    sommet: "Col d'Ayous (2 185 m) + passage en Espagne",
    balisage: "GR 10 France + GR 11 Espagne",
    eau: "Refuges Pombie, Respomuso + sources altitude",
    ravito: "Refuge de Pombie (Espagne) — repas disponibles",
    carte: "IGN 1547 OT + Editorial Alpina n°25",
    description: "Le tour du Pic du Midi d'Ossau (2 884 m) est le circuit de référence des Pyrénées béarnaises. On franchit la frontière franco-espagnole, on bivouaque côté Aragon, et on tourne autour du géant en admirant ses faces nord et sud — une expérience inoubliable.",
    etapes: [
      { jour: "J1", troncon: "Bious-Artigues → Col d'Ayous → Refuge d'Ayous → Portalet", km: "16 km", deni: "+1 200/−600 m", bivouac: "Refuge d'Ayous (2 185 m)" },
      { jour: "J2", troncon: "Portalet → Refuge de Pombie (versant espagnol)", km: "15 km", deni: "+950/−850 m", bivouac: "Refuge de Pombie (2 040 m)" },
      { jour: "J3", troncon: "Pombie → Col de Peyreget → Tour versant sud → Lac de Peyreget", km: "17 km", deni: "+1 100/−1 000 m", bivouac: "Lac de Peyreget (2 000 m)" },
      { jour: "J4", troncon: "Lac de Peyreget → Col Long de Magnabaigt → Bious-Artigues", km: "14 km", deni: "+550/−1 350 m", bivouac: "Retour au point de départ" },
    ],
    tips: [
      "Passage en Espagne (J2) : aucune formalité pour les citoyens européens.",
      "Le Refuge de Pombie propose repas et ravitaillement — idéal pour alléger le sac.",
      "Les vautours fauves survolent en permanence cette zone — spectacle garanti !",
    ],
    links: [
      { icon: "⛺", label: "Refuge d'Ayous", url: "https://www.refuge-ayous.com", note: "Réservation en ligne" },
      { icon: "⛺", label: "Refugio de Pombie", url: "https://www.refugiodepombie.com", note: "Côté Aragon" },
      { icon: "📷", label: "Altituderando – Midi Ossau", url: "https://www.altituderando.com/Tour-du-Pic-du-Midi-d-Ossau", note: "Description complète" },
    ],
    highlights: ["Traversée France-Espagne", "Autour du Midi d'Ossau (2 884 m)", "Vautours fauves"],
  },
];

// ── RANDOS JOURNÉE ──────────────────────────────────────────
const RANDOS_JOURNEE = [
  {
    id: 10, slug: "la-rhune-sare",
    emoji: "🚂", title: "La Rhune depuis Sare",
    region: "Labourd · Pays Basque", zone: "paysbasque",
    type: "journee", level: "modere", levelLabel: "Modéré",
    distance: "10 km", duree: "4h", denivelé: "800 m",
    distanceBayonne: "40 min de Bayonne",
    img: "https://images.unsplash.com/photo-1500534314209-a25ddb2bd429?w=800&q=80",
    description: "Sommet emblématique du Pays Basque (905 m), accessible via le GR 10 depuis Sare. Vue à 360° sur l'Atlantique, la côte basque et les Pyrénées. En bonus : le célèbre petit train à crémaillère centenaire.",
    depart: "Village de Sare — parking gratuit (43.304179, -1.594296)",
    balisage: "GR 10 rouge/blanc jusqu'au sommet",
    highlights: ["Vue 360° Atlantique + Pyrénées", "Petit train centenaire (option)", "Pottoks au sommet"],
    links: [
      { icon: "🗺️", label: "Topo Topopyrenees", url: "https://www.topopyrenees.com/la-rhune-905m-en-boucle-depuis-le-village-de-sare/" },
      { icon: "📍", label: "AllTrails", url: "https://www.alltrails.com/fr/randonnee/france/pyrenees-atlantiques/sare-la-rhune" },
      { icon: "🚂", label: "Train de la Rhune", url: "https://www.rhune.com/fr/infos-pratiques" },
    ],
  },
  {
    id: 11, slug: "mondarrain-ainhoa",
    emoji: "🐄", title: "Pic du Mondarrain depuis Ainhoa",
    region: "Labourd · Pays Basque", zone: "paysbasque",
    type: "journee", level: "modere", levelLabel: "Modéré",
    distance: "13,5 km", duree: "4h–5h", denivelé: "650 m",
    distanceBayonne: "35 min de Bayonne",
    img: "https://images.unsplash.com/photo-1441974231531-c6227db76b6e?w=800&q=80",
    description: "Le Mondarrain (749 m) depuis le plus beau village du Pays Basque. La montée passe par le chemin de croix d'Ainhoa, traverse des pâturages gardés par les Betizu (vaches sauvages classées Natura 2000), et offre une vue jusqu'à la mer.",
    depart: "Ainhoa (64250) — parking près de l'office de tourisme",
    balisage: "GR 10 + sentiers balisés jaune",
    highlights: ["Village classé + beau de France", "Vaches Betizu (Natura 2000)", "Panorama mer + montagnes"],
    links: [
      { icon: "🗺️", label: "Rando Pays Basque", url: "https://rando-pays-basque.info/le-mondarrain-depuis-ainhoa/" },
      { icon: "📍", label: "Visorando", url: "https://www.visorando.com/randonnee-mondarrain.html" },
    ],
  },
  {
    id: 12, slug: "mont-ursuya-hasparren",
    emoji: "🦅", title: "Mont Ursuya depuis Hasparren",
    region: "Labourd · Pays Basque", zone: "paysbasque",
    type: "journee", level: "modere", levelLabel: "Modéré",
    distance: "12,9 km", duree: "4h30–5h", denivelé: "566 m",
    distanceBayonne: "25 min de Bayonne",
    img: "https://images.unsplash.com/photo-1508739773434-c26b3d09e071?w=800&q=80",
    description: "Le Mont Ursuya (681 m), belvédère isolé du reste de la chaîne, domine les plaines basques et béarnaises. Par temps clair, vue jusqu'à l'Ossau et au Pic du Midi de Bigorre. La rando la plus proche de Bayonne !",
    depart: "Hasparren — quartier Zelhaia (parking fronton)",
    balisage: "PR local Bidegaraia — balisage jaune",
    highlights: ["25 min de Bayonne seulement", "Vue sur Béarn et Labourd", "Peu fréquenté, calme"],
    links: [
      { icon: "📷", label: "Altituderando", url: "https://www.altituderando.com/Ursuya-681m-par-Zelhaia-Hasparren" },
      { icon: "📍", label: "AllTrails", url: "https://www.alltrails.com/fr/randonnee/france/pyrenees-atlantiques/hasparren-mont-ursuya" },
    ],
  },
  {
    id: 13, slug: "corniche-basque",
    emoji: "🌊", title: "Corniche Basque – Sentier du Littoral",
    region: "Côte Basque", zone: "paysbasque",
    type: "journee", level: "facile", levelLabel: "Facile",
    distance: "15 km", duree: "5h–6h", denivelé: "400 m",
    distanceBayonne: "30 min de Bayonne",
    img: "https://images.unsplash.com/photo-1507525428034-b723cf961d3e?w=800&q=80",
    description: "De Bidart à Hendaye, 15 km de falaises sauvages et de panoramas sur l'Atlantique. Le sentier du littoral longe la côte basque encore préservée, entre calanques, criques cachées et vues sur les Pyrénées. Zéro altitude, 100% mer.",
    depart: "Bidart (64210) — parking de la plage du Centre",
    balisage: "GR 121 rouge/blanc — bien balisé",
    highlights: ["Falaises et criques sauvages", "Vue Pyrénées côté mer", "Faune marine"],
    links: [
      { icon: "🌊", label: "Guide du Pays Basque", url: "https://www.guide-du-paysbasque.com/fr/experiences/sportive/article-les-plus-belles-randonnees-du-pays-basque--131.html" },
    ],
  },
];

// ── MATÉRIEL ─────────────────────────────────────────────────
const MATERIEL = [
  { icon: "🏕️", name: "Tente 3 saisons légère (2–3 pers.)", prio: "rouge", pLabel: "Indispensable", prix: "80–250 €", ou: "Décathlon, MSR, Salomon" },
  { icon: "🛌", name: "Sac de couchage (confort 0°C à −5°C)", prio: "rouge", pLabel: "Indispensable", prix: "60–200 €", ou: "Décathlon Forclaz, Vaude, Rab" },
  { icon: "🛏️", name: "Matelas isolant (Thermarest ou mousse)", prio: "rouge", pLabel: "Indispensable", prix: "20–80 €", ou: "Décathlon, Sea to Summit" },
  { icon: "💧", name: "Filtre à eau (Sawyer Squeeze ou Katadyn)", prio: "orange", pLabel: "Très utile", prix: "30–60 €", ou: "Décathlon, Amazon" },
  { icon: "🍳", name: "Réchaud + gaz + casserole légère", prio: "orange", pLabel: "Très utile", prix: "30–80 €", ou: "MSR, Jetboil, Décathlon" },
  { icon: "🥘", name: "Nourriture lyophilisée / déshydratée", prio: "orange", pLabel: "Très utile", prix: "5–12 €/repas", ou: "Freeze-dry.fr, Trek'n'Eat" },
  { icon: "🧃", name: "Gourde 1L + poche à eau 2L", prio: "orange", pLabel: "Très utile", prix: "10–30 €", ou: "Nalgene, Hydrapak" },
  { icon: "🔦", name: "Lampe frontale + piles de rechange", prio: "jaune", pLabel: "Utile", prix: "15–40 €", ou: "Petzl, Black Diamond" },
  { icon: "🩹", name: "Trousse de premiers secours", prio: "jaune", pLabel: "Utile", prix: "15–30 €", ou: "Pharmacie, Décathlon" },
  { icon: "📱", name: "App GPS offline (Maps.me / OruxMaps)", prio: "jaune", pLabel: "Utile", prix: "Gratuit", ou: "Téléchargez avant de partir !" },
  { icon: "🧴", name: "Crème solaire SPF 50+ + anti-insectes", prio: "jaune", pLabel: "Utile", prix: "10–20 €", ou: "Pharmacie, supermarché" },
  { icon: "🧦", name: "Vêtements de rechange + couche chaude", prio: "orange", pLabel: "Très utile", prix: "Variable", ou: "Polaire ou doudoune légère" },
];

const URGENCES = [
  { label: "Urgence universelle", num: "112", note: "Fonctionne même sans réseau" },
  { label: "PGHM Pau", num: "05 62 92 41 41", note: "Secours montagne Pyrénées-Atlantiques" },
  { label: "PGHM Tarbes", num: "05 62 44 04 44", note: "Secours montagne Hautes-Pyrénées" },
];